/*
 * Copyright (c) 2026 Realtek Semiconductor Corp.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#include "cap_board_mgr.h"
#include "claw_cap.h"
#include "claw_agent.h"
#include <cJSON.h>
#include "platform_stdlib.h"
#include "os_wrapper.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>

/* Embedded chip JSON symbols (per chip, generated by CMake) */
extern const unsigned char _res_chip_RTL8721F_start[];
extern const unsigned char _res_chip_RTL8721F_end[];

/* Embedded board JSON symbols + registry table — auto-generated by CMake */
#include "board_registry.h"

#define TAG              "cap_board_mgr"
#define VFS_DEFAULT_PATH "vfs:/board.json"
#define MAX_DEVICES      16
#define MAX_IFACES        8
#define MAX_AVAIL_PINS   64

/* ---- Embedded resource lookup table ---- */

typedef struct {
    const char         *name;
    const unsigned char *start;
    const unsigned char *end;
} res_entry_t;

static const res_entry_t s_chips[] = {
    { "RTL8721F", _res_chip_RTL8721F_start, _res_chip_RTL8721F_end },
    { NULL, NULL, NULL }  /* sentinel */
};

static const res_entry_t s_boards[] = {
    BOARD_REGISTRY_ENTRIES
};

static char *load_embedded_res(const res_entry_t *table, const char *name)
{
    for (int i = 0; table[i].name; i++) {
        if (strcmp(table[i].name, name) == 0) {
            size_t len = (size_t)(table[i].end - table[i].start);
            char *buf = rtos_mem_malloc(len + 1);
            if (buf) {
                memcpy(buf, table[i].start, len);
                buf[len] = '\0';
            }
            return buf;
        }
    }
    return NULL;
}

/* ---- Model types ---- */

typedef struct {
    char id[32];
    char name[64];
    char type[32];
    char chip[32];
    char lua_module[32];
    char iface_id[32];
    cJSON      *params_obj;   /* pointer into s_model.root — do not free */
    const char *notes;        /* points into JSON string — do not free */
    const char *usage_guide;  /* points into JSON string — do not free */
} brd_device_t;

typedef struct {
    char   id[32];
    char   type[16];
    char   instance[16];
    cJSON *obj;               /* original cJSON object inside s_model.root */
} brd_iface_t;

/*
 * All board cap execute functions are invoked serially by the claw_agent
 * capability dispatcher (single-threaded cap execution). board_reload
 * (cap_board_mgr_init) therefore runs exclusively — no concurrent reader
 * can be accessing s_model while a reload is in progress.
 * If that serialization guarantee is ever lifted, access to s_model must
 * be protected by a mutex.
 */
static struct {
    char         board_name[64];
    char         vfs_path[64];   /* original path from init config */
    brd_device_t devices[MAX_DEVICES];
    int          n_devices;
    brd_iface_t  ifaces[MAX_IFACES];
    int          n_ifaces;
    cJSON       *chip_constraints;
    cJSON       *root;
    bool         loaded;
} s_model;

/* Pre-computed: board_pins.available minus chip_constraints.system_reserved */
static char s_avail_pins[MAX_AVAIL_PINS][16];
static int  s_n_avail_pins = 0;

static bool s_group_registered = false;

/* ---- Helpers ---- */

static void str_copy(char *dst, size_t dsz, cJSON *obj, const char *key)
{
    cJSON *item = cJSON_GetObjectItem(obj, key);
    if (item && cJSON_IsString(item) && item->valuestring) {
        strlcpy(dst, item->valuestring, dsz);
    }
}

static char *read_vfs_file(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (sz <= 0 || sz > 65536) { fclose(f); return NULL; }
    char *buf = rtos_mem_malloc((size_t)sz + 1);
    if (!buf) { fclose(f); return NULL; }
    size_t got = fread(buf, 1, (size_t)sz, f);
    buf[got] = '\0';
    fclose(f);
    return buf;
}

static bool write_vfs_file(const char *path, const char *content)
{
    size_t len = strlen(content);

    /* Retry: VFS may not accept writes immediately after FS init */
    for (int retry = 0; retry < 3; retry++) {
        if (retry > 0) {
            rtos_time_delay_ms(200);
        }
        FILE *f = fopen(path, "w");
        if (!f) { continue; }
        size_t written = fwrite(content, 1, len, f);
        int cr = fclose(f);
        if (written == len && cr == 0) {
            return true;
        }
    }
    return false;
}

/* ---- board_merge: runtime merge of base + overlay ---- */

/*
 * Find and remove an array item by "id" field.
 * Returns the removed item (or NULL). Caller must cJSON_Delete it.
 */
static cJSON *remove_array_item_by_id(cJSON *arr, const char *id)
{
    int idx = 0;
    cJSON *item;
    cJSON_ArrayForEach(item, arr) {
        cJSON *id_item = cJSON_GetObjectItem(item, "id");
        if (id_item && cJSON_IsString(id_item)
                && strcmp(id_item->valuestring, id) == 0) {
            return cJSON_DetachItemFromArray(arr, idx);
        }
        idx++;
    }
    return NULL;
}

/*
 * Merge interface/device arrays by "id".
 * Rules:
 *   - overlay item with "$op":"remove" → remove from base (by id)
 *   - overlay item with existing id  → replace in base
 *   - overlay item with new id     → append to base
 */
static void merge_arrays_by_id(cJSON *base_arr, cJSON *overlay_arr)
{
    if (!cJSON_IsArray(base_arr) || !cJSON_IsArray(overlay_arr)) return;

    cJSON *item;
    cJSON_ArrayForEach(item, overlay_arr) {
        cJSON *id_item = cJSON_GetObjectItem(item, "id");
        if (!id_item || !cJSON_IsString(id_item) || !id_item->valuestring)
            continue;

        const char *id = id_item->valuestring;

        /* Check for $op: remove */
        cJSON *op_item = cJSON_GetObjectItem(item, "$op");
        if (op_item && cJSON_IsString(op_item)
                && strcmp(op_item->valuestring, "remove") == 0) {
            cJSON *removed = remove_array_item_by_id(base_arr, id);
            if (removed) cJSON_Delete(removed);
            continue;
        }

        /* Try to find existing item in base */
        cJSON *existing = NULL;
        cJSON *base_item;
        cJSON_ArrayForEach(base_item, base_arr) {
            cJSON *bid = cJSON_GetObjectItem(base_item, "id");
            if (bid && cJSON_IsString(bid)
                    && bid->valuestring
                    && strcmp(bid->valuestring, id) == 0) {
                existing = base_item;
                break;
            }
        }

        if (existing) {
            /* Replace: remove existing, insert duplicate of overlay */
            cJSON *dup = cJSON_Duplicate(item, 1);
            if (dup) {
                /* Remove $op from the inserted item if present */
                cJSON_DeleteItemFromObject(dup, "$op");
                cJSON_ReplaceItemViaPointer(base_arr, existing, dup);
            }
        } else {
            /* Append new item */
            cJSON *dup = cJSON_Duplicate(item, 1);
            if (dup) {
                cJSON_DeleteItemFromObject(dup, "$op");
                cJSON_AddItemToArray(base_arr, dup);
            }
        }
    }
}

/*
 * Merge board_pins objects:
 *   - "available" array      → merge/append dedup
 *   - "remove_pins" array    → remove named pins from base "available"
 *   - other scalar fields    → overlay wins
 */
static void merge_board_pins(cJSON *base_bp, cJSON *overlay_bp)
{
    cJSON *base_avail = cJSON_GetObjectItem(base_bp, "available");

    /* Handle "available" array: append pins not already in base.
     * If base has no "available" key yet, create it so overlay pins are not lost. */
    cJSON *ov_avail = cJSON_GetObjectItem(overlay_bp, "available");
    if (ov_avail && cJSON_IsArray(ov_avail)) {
        if (!base_avail || !cJSON_IsArray(base_avail)) {
            base_avail = cJSON_CreateArray();
            if (base_avail) cJSON_AddItemToObject(base_bp, "available", base_avail);
        }
        if (base_avail && cJSON_IsArray(base_avail)) {
            cJSON *pin;
            cJSON_ArrayForEach(pin, ov_avail) {
                if (!pin->valuestring) continue;
                bool found = false;
                cJSON *bp;
                cJSON_ArrayForEach(bp, base_avail) {
                    if (bp->valuestring && strcmp(bp->valuestring, pin->valuestring) == 0) {
                        found = true;
                        break;
                    }
                }
                if (!found) {
                    cJSON *dup = cJSON_Duplicate(pin, 1);
                    if (dup) cJSON_AddItemToArray(base_avail, dup);
                }
            }
        }
    }

    /* Handle "remove_pins" array: remove specified pins from base */
    cJSON *rm_pins = cJSON_GetObjectItem(overlay_bp, "remove_pins");
    if (rm_pins && cJSON_IsArray(rm_pins) && base_avail && cJSON_IsArray(base_avail)) {
        cJSON *rp;
        cJSON_ArrayForEach(rp, rm_pins) {
            if (!rp->valuestring) continue;
            int idx = 0;
            cJSON *bp;
            cJSON_ArrayForEach(bp, base_avail) {
                if (bp->valuestring && strcmp(bp->valuestring, rp->valuestring) == 0) {
                    cJSON *removed = cJSON_DetachItemFromArray(base_avail, idx);
                    if (removed) cJSON_Delete(removed);
                    break;
                }
                idx++;
            }
        }
    }

    /* Merge scalar fields (excluding "available" and "remove_pins") */
    cJSON *field;
    cJSON_ArrayForEach(field, overlay_bp) {
        if (!field->string) continue;
        if (strcmp(field->string, "available")   == 0) continue;
        if (strcmp(field->string, "remove_pins") == 0) continue;
        cJSON_DeleteItemFromObject(base_bp, field->string);
        cJSON *dup = cJSON_Duplicate(field, 1);
        if (dup) cJSON_AddItemToObject(base_bp, field->string, dup);
    }
}

/*
 * Merge two authoring-format board JSON trees.
 * base and overlay remain owned by caller.
 * Returns a newly allocated cJSON tree on success, NULL on failure.
 */
static cJSON *board_merge(cJSON *base, cJSON *overlay)
{
    if (!overlay) {
        return base ? cJSON_Duplicate(base, 1) : NULL;
    }
    if (!base) {
        /* No base = just duplicate overlay (will still process $ fields) */
        cJSON *dup = cJSON_Duplicate(overlay, 1);
        /* Remove $ fields */
        cJSON_DeleteItemFromObject(dup, "$chip");
        cJSON_DeleteItemFromObject(dup, "$extends");
        return dup;
    }

    cJSON *result = cJSON_Duplicate(base, 1);
    if (!result) return NULL;

    cJSON *child = overlay->child;
    while (child) {
        if (!child->string) { child = child->next; continue; }
        const char *key = child->string;

        /* Skip directive fields (handled by board_resolve) */
        if (key[0] == '$') { child = child->next; continue; }

        cJSON *existing = cJSON_GetObjectItem(result, key);

        if (existing && cJSON_IsArray(child)
                && (strcmp(key, "interfaces") == 0
                    || strcmp(key, "devices") == 0)) {
            /* Merge arrays by "id" */
            if (cJSON_IsArray(existing)) {
                merge_arrays_by_id(existing, child);
            }
        } else if (existing && cJSON_IsObject(child)
                   && strcmp(key, "board_pins") == 0) {
            if (cJSON_IsObject(existing)) {
                merge_board_pins(existing, child);
            }
        } else if (existing && cJSON_IsObject(child) && cJSON_IsObject(existing)) {
            /* For other objects (like "board"), merge field by field */
            cJSON *sub = child->child;
            while (sub) {
                if (sub->string) {
                    cJSON_DeleteItemFromObject(existing, sub->string);
                    cJSON *dup = cJSON_Duplicate(sub, 1);
                    if (dup) cJSON_AddItemToObject(existing, sub->string, dup);
                }
                sub = sub->next;
            }
        } else {
            /* Override scalar or replace array */
            cJSON_DeleteItemFromObject(result, key);
            cJSON *dup = cJSON_Duplicate(child, 1);
            if (dup) cJSON_AddItemToObject(result, key, dup);
        }

        child = child->next;
    }

    /* Remove any $op fields from devices/interfaces that got duplicated from overlay */
    cJSON *dev_arr = cJSON_GetObjectItem(result, "devices");
    if (dev_arr && cJSON_IsArray(dev_arr)) {
        cJSON *dev;
        cJSON_ArrayForEach(dev, dev_arr) {
            cJSON_DeleteItemFromObject(dev, "$op");
        }
    }
    cJSON *if_arr = cJSON_GetObjectItem(result, "interfaces");
    if (if_arr && cJSON_IsArray(if_arr)) {
        cJSON *iface;
        cJSON_ArrayForEach(iface, if_arr) {
            cJSON_DeleteItemFromObject(iface, "$op");
        }
    }

    return result;
}

/* ---- board_resolve: handle $chip / $extends directives ---- */

/*
 * Resolve authoring-format board JSON into deployable format:
 *   1. Follow $extends → load built-in board, merge recursively
 *   2. Follow $chip → load chip JSON, insert as "chip_constraints"
 *   3. Remove $chip/$extends directive fields
 *
 * Caller takes ownership of the returned cJSON and must free root separately.
 */
static cJSON *board_resolve(cJSON *root)
{
    cJSON *result = NULL;
    cJSON *base = NULL;
    char chip_name[64] = {0};

    /* Save $chip from root (user's board) first — this takes priority */
    cJSON *chip_item = cJSON_GetObjectItem(root, "$chip");
    if (chip_item && cJSON_IsString(chip_item) && chip_item->valuestring) {
        strlcpy(chip_name, chip_item->valuestring, sizeof(chip_name));
    }

    /* Step 1: resolve $extends */
    cJSON *extends_item = cJSON_GetObjectItem(root, "$extends");
    if (extends_item && cJSON_IsString(extends_item) && extends_item->valuestring
            && extends_item->valuestring[0] != '\0') {
        const char *extends_name = extends_item->valuestring;
        /* Guard: self-reference would cause infinite recursion */
        cJSON *board_obj = cJSON_GetObjectItem(root, "board");
        cJSON *name_item = board_obj ? cJSON_GetObjectItem(board_obj, "name") : NULL;
        if (name_item && cJSON_IsString(name_item) &&
                strcmp(name_item->valuestring, extends_name) == 0) {
            RTK_LOGE(TAG, "[board_mgr] $extends '%s' is self-referential, ignored\n", extends_name);
            goto skip_extends;
        }
        char *base_str = load_embedded_res(s_boards, extends_name);
        if (base_str) {
            base = cJSON_Parse(base_str);
            rtos_mem_free(base_str);
            if (base) {
                /* Inherit $chip from base if root didn't specify one */
                if (chip_name[0] == '\0') {
                    cJSON *base_chip = cJSON_GetObjectItem(base, "$chip");
                    if (base_chip && cJSON_IsString(base_chip) && base_chip->valuestring) {
                        strlcpy(chip_name, base_chip->valuestring, sizeof(chip_name));
                    }
                }
                /* Recursively resolve the base first */
                cJSON *resolved_base = board_resolve(base);
                if (resolved_base) {
                    cJSON_Delete(base);
                    base = resolved_base;
                }
            } else {
                RTK_LOGE(TAG, "[board_mgr] Failed to parse extended board '%s'\n", extends_name);
            }
        } else {
            RTK_LOGE(TAG, "[board_mgr] Unknown board in $extends: '%s'\n", extends_name);
        }
    }
skip_extends:;

    /* Step 2: merge base + overlay */
    result = board_merge(base, root);
    if (base) cJSON_Delete(base);

    if (!result) {
        result = cJSON_Duplicate(root, 1);
    }

    /* Step 3: resolve $chip → chip_constraints */
    if (chip_name[0] != '\0') {
        char *chip_str = load_embedded_res(s_chips, chip_name);
        if (chip_str) {
            cJSON *chip_json = cJSON_Parse(chip_str);
            rtos_mem_free(chip_str);
            if (chip_json) {
                /* Replace any chip_constraints inherited from a resolved base
                 * so that an explicit $chip on the overlay always wins. */
                cJSON_DeleteItemFromObject(result, "chip_constraints");
                cJSON_AddItemToObject(result, "chip_constraints", chip_json);
                RTK_LOGI(TAG, "[board_mgr] Resolved chip: %s\n", chip_name);
            } else {
                RTK_LOGE(TAG, "[board_mgr] Failed to parse chip JSON: %s\n", chip_name);
            }
        } else {
            RTK_LOGE(TAG, "[board_mgr] Unknown chip: '%s'\n", chip_name);
        }
    }

    /* Step 4: remove directive fields from result */
    if (result) {
        cJSON_DeleteItemFromObject(result, "$chip");
        cJSON_DeleteItemFromObject(result, "$extends");
    }

    return result;
}

/* ---- Build model from resolved JSON ---- */

static bool build_model(cJSON *root)
{
    cJSON *board = cJSON_GetObjectItem(root, "board");
    if (!board) return false;

    str_copy(s_model.board_name, sizeof(s_model.board_name), board, "name");

    s_model.chip_constraints = cJSON_GetObjectItem(root, "chip_constraints");

    /* Parse interfaces array */
    cJSON *ifaces_arr = cJSON_GetObjectItem(root, "interfaces");
    s_model.n_ifaces = 0;
    if (ifaces_arr && cJSON_IsArray(ifaces_arr)) {
        cJSON *iface;
        cJSON_ArrayForEach(iface, ifaces_arr) {
            if (s_model.n_ifaces >= MAX_IFACES) {
                RTK_LOGW(TAG, "[board_mgr] interfaces truncated at %d (MAX_IFACES), extra entries ignored\n",
                         MAX_IFACES);
                break;
            }
            brd_iface_t *bi = &s_model.ifaces[s_model.n_ifaces++];
            str_copy(bi->id,       sizeof(bi->id),       iface, "id");
            str_copy(bi->type,     sizeof(bi->type),     iface, "type");
            str_copy(bi->instance, sizeof(bi->instance), iface, "instance");
            bi->obj = iface;
        }
    }

    /* Parse devices array */
    cJSON *devs_arr = cJSON_GetObjectItem(root, "devices");
    s_model.n_devices = 0;
    if (devs_arr && cJSON_IsArray(devs_arr)) {
        cJSON *dev;
        cJSON_ArrayForEach(dev, devs_arr) {
            if (s_model.n_devices >= MAX_DEVICES) {
                RTK_LOGW(TAG, "[board_mgr] devices truncated at %d (MAX_DEVICES), extra entries ignored\n",
                         MAX_DEVICES);
                break;
            }
            brd_device_t *bd = &s_model.devices[s_model.n_devices++];
            str_copy(bd->id,         sizeof(bd->id),         dev, "id");
            str_copy(bd->name,       sizeof(bd->name),       dev, "name");
            str_copy(bd->type,       sizeof(bd->type),       dev, "type");
            str_copy(bd->chip,       sizeof(bd->chip),       dev, "chip");
            str_copy(bd->lua_module, sizeof(bd->lua_module), dev, "lua_module");
            str_copy(bd->iface_id,   sizeof(bd->iface_id),   dev, "interface");

            bd->params_obj = cJSON_GetObjectItem(dev, "params");

            cJSON *notes_item = cJSON_GetObjectItem(dev, "notes");
            bd->notes = (notes_item && cJSON_IsString(notes_item))
                        ? notes_item->valuestring : NULL;

            cJSON *guide_item = cJSON_GetObjectItem(dev, "usage_guide");
            bd->usage_guide = (guide_item && cJSON_IsString(guide_item))
                              ? guide_item->valuestring : NULL;
        }
    }

    /* Pre-compute available pins: board_pins.available - system_reserved */
    cJSON *bp        = cJSON_GetObjectItem(root, "board_pins");
    cJSON *avail_arr = bp ? cJSON_GetObjectItem(bp, "available") : NULL;
    cJSON *sysres    = s_model.chip_constraints
                       ? cJSON_GetObjectItem(s_model.chip_constraints, "system_reserved")
                       : NULL;
    s_n_avail_pins = 0;
    if (avail_arr && cJSON_IsArray(avail_arr)) {
        cJSON *pin;
        cJSON_ArrayForEach(pin, avail_arr) {
            if (!pin->valuestring) continue;
            if (s_n_avail_pins >= MAX_AVAIL_PINS) {
                RTK_LOGW(TAG, "[board_mgr] available pins truncated at %d (MAX_AVAIL_PINS), extra entries ignored\n",
                         MAX_AVAIL_PINS);
                break;
            }
            bool reserved = false;
            if (sysres && cJSON_IsArray(sysres)) {
                cJSON *rp;
                cJSON_ArrayForEach(rp, sysres) {
                    if (rp->valuestring && strcmp(rp->valuestring, pin->valuestring) == 0) {
                        reserved = true;
                        break;
                    }
                }
            }
            if (!reserved) {
                strlcpy(s_avail_pins[s_n_avail_pins], pin->valuestring,
                        sizeof(s_avail_pins[0]));
                s_n_avail_pins++;
            }
        }
    }

    s_model.root   = root;
    s_model.loaded = true;
    return true;
}

/* ---- Cap execute functions ---- */

static int execute_board_list_devices(const char *input_json,
                                      const claw_cap_call_context_t *ctx,
                                      char **output)
{
    (void)input_json;
    (void)ctx;

    if (!s_model.loaded) {
        return claw_cap_set_output(output, "{\"error\":\"board not loaded\"}");
    }

    cJSON *resp = cJSON_CreateObject();
    if (!resp) return RTK_ERR_NOMEM;

    cJSON_AddStringToObject(resp, "board", s_model.board_name);
    cJSON *arr = cJSON_CreateArray();
    cJSON_AddItemToObject(resp, "devices", arr);

    for (int i = 0; i < s_model.n_devices; i++) {
        brd_device_t *d = &s_model.devices[i];
        cJSON *item = cJSON_CreateObject();
        cJSON_AddStringToObject(item, "id",        d->id);
        cJSON_AddStringToObject(item, "name",      d->name);
        cJSON_AddStringToObject(item, "type",      d->type);
        cJSON_AddStringToObject(item, "chip",      d->chip);
        cJSON_AddStringToObject(item, "interface", d->iface_id);
        if (d->lua_module[0])
            cJSON_AddStringToObject(item, "lua_module", d->lua_module);
        cJSON_AddItemToArray(arr, item);
    }

    char *out = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);
    if (!out) { *output = NULL; return RTK_ERR_NOMEM; }
    *output = out;
    return RTK_SUCCESS;
}

static int execute_board_get_device(const char *input_json,
                                    const claw_cap_call_context_t *ctx,
                                    char **output)
{
    (void)ctx;

    if (!s_model.loaded) {
        return claw_cap_set_output(output, "{\"error\":\"board not loaded\"}");
    }

    char dev_id_buf[32] = {0};
    cJSON *req = cJSON_Parse(input_json);
    if (req) {
        cJSON *id_item = cJSON_GetObjectItem(req, "id");
        if (id_item && cJSON_IsString(id_item) && id_item->valuestring)
            strlcpy(dev_id_buf, id_item->valuestring, sizeof(dev_id_buf));
    }
    cJSON_Delete(req);
    req = NULL;

    if (!dev_id_buf[0]) {
        return claw_cap_set_output(output, "{\"error\":\"missing id parameter\"}");
    }

    brd_device_t *found = NULL;
    for (int i = 0; i < s_model.n_devices; i++) {
        if (strcmp(s_model.devices[i].id, dev_id_buf) == 0) {
            found = &s_model.devices[i];
            break;
        }
    }

    if (!found) {
        cJSON *err = cJSON_CreateObject();
        if (!err) return RTK_ERR_NOMEM;
        cJSON_AddStringToObject(err, "error", "device not found");
        cJSON_AddStringToObject(err, "id", dev_id_buf);
        char *out = cJSON_PrintUnformatted(err);
        cJSON_Delete(err);
        if (!out) return RTK_ERR_NOMEM;
        *output = out;
        return RTK_SUCCESS;
    }

    cJSON *resp = cJSON_CreateObject();
    if (!resp) { return RTK_ERR_NOMEM; }

    cJSON_AddStringToObject(resp, "id",   found->id);
    cJSON_AddStringToObject(resp, "name", found->name);
    cJSON_AddStringToObject(resp, "type", found->type);
    cJSON_AddStringToObject(resp, "chip", found->chip);
    if (found->lua_module[0])
        cJSON_AddStringToObject(resp, "lua_module", found->lua_module);

    /* Inline resolved interface so AI gets everything in one call */
    if (found->iface_id[0]) {
        bool iface_found = false;
        for (int j = 0; j < s_model.n_ifaces; j++) {
            if (strcmp(s_model.ifaces[j].id, found->iface_id) == 0) {
                cJSON *iface_copy = cJSON_Duplicate(s_model.ifaces[j].obj, 1);
                if (iface_copy)
                    cJSON_AddItemToObject(resp, "interface", iface_copy);
                iface_found = true;
                break;
            }
        }
        if (!iface_found) {
            RTK_LOGW(TAG, "[board_mgr] device '%s' references unknown interface '%s'\n",
                     found->id, found->iface_id);
            cJSON_AddStringToObject(resp, "interface_error",
                                    "interface not found — board.json may have a typo or the interface was truncated");
        }
    }

    if (found->params_obj) {
        cJSON *params_copy = cJSON_Duplicate(found->params_obj, 1);
        if (params_copy)
            cJSON_AddItemToObject(resp, "params", params_copy);
    }

    if (found->notes)
        cJSON_AddStringToObject(resp, "notes", found->notes);
    if (found->usage_guide)
        cJSON_AddStringToObject(resp, "usage_guide", found->usage_guide);

    char *out = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);
    if (!out) { *output = NULL; return RTK_ERR_NOMEM; }
    *output = out;
    return RTK_SUCCESS;
}

/* Case-insensitive string compare (avoids strcasecmp portability issues) */
static int str_icmp(const char *a, const char *b)
{
    while (*a && *b) {
        int ca = tolower((unsigned char)*a++);
        int cb = tolower((unsigned char)*b++);
        if (ca != cb) return ca - cb;
    }
    return tolower((unsigned char)*a) - tolower((unsigned char)*b);
}

/*
 * Locate a peripheral type object in chip_constraints.
 * Accepts both type names ("spi") and instance names ("SPI0"/"spi0").
 * Returns the cJSON peripheral object and writes the canonical type name
 * into type_out. Returns NULL if not found or not supported.
 */
static cJSON *periph_find_type(const char *input, char *type_out, size_t type_sz)
{
    if (!s_model.chip_constraints || !input) return NULL;

    cJSON *item = s_model.chip_constraints->child;

    /* Pass 1: direct type-name match (case-insensitive) */
    while (item) {
        const char *key = item->string;
        if (key && key[0] != '_' && strcmp(key, "system_reserved") != 0
                && str_icmp(key, input) == 0) {
            if (type_out) strlcpy(type_out, key, type_sz);
            return item;
        }
        item = item->next;
    }

    /* Pass 2: match against instance names inside each type */
    item = s_model.chip_constraints->child;
    while (item) {
        const char *key = item->string;
        if (key && key[0] != '_' && strcmp(key, "system_reserved") != 0
                && cJSON_IsObject(item)) {
            cJSON *insts = cJSON_GetObjectItem(item, "instances");
            if (insts && cJSON_IsArray(insts)) {
                cJSON *inst;
                cJSON_ArrayForEach(inst, insts) {
                    if (inst->valuestring && str_icmp(inst->valuestring, input) == 0) {
                        if (type_out) strlcpy(type_out, key, type_sz);
                        return item;
                    }
                }
            }
        }
        item = item->next;
    }
    return NULL;
}

static int execute_board_query_peripheral(const char *input_json,
                                          const claw_cap_call_context_t *ctx,
                                          char **output)
{
    (void)ctx;

    if (!s_model.loaded) {
        return claw_cap_set_output(output, "{\"error\":\"board not loaded\"}");
    }

    const char *peripheral = NULL;
    cJSON *req = cJSON_Parse(input_json);
    if (req) {
        cJSON *p = cJSON_GetObjectItem(req, "peripheral");
        if (p && cJSON_IsString(p))
            peripheral = p->valuestring;
    }

    if (!peripheral) {
        cJSON_Delete(req);
        return claw_cap_set_output(output, "{\"error\":\"missing peripheral parameter\"}");
    }

    char type_name[32] = {0};
    cJSON *periph_obj = periph_find_type(peripheral, type_name, sizeof(type_name));

    if (!periph_obj) {
        cJSON *err = cJSON_CreateObject();
        if (!err) { cJSON_Delete(req); return RTK_ERR_NOMEM; }
        cJSON_AddFalseToObject(err, "supported");
        cJSON_AddStringToObject(err, "peripheral", peripheral);
        char *out = cJSON_PrintUnformatted(err);
        cJSON_Delete(err);
        cJSON_Delete(req);
        if (!out) return RTK_ERR_NOMEM;
        *output = out;
        return RTK_SUCCESS;
    }

    cJSON *resp = cJSON_CreateObject();
    if (!resp) { cJSON_Delete(req); return RTK_ERR_NOMEM; }

    cJSON_AddTrueToObject(resp, "supported");
    cJSON_AddStringToObject(resp, "peripheral", type_name);

    /* Optional note */
    cJSON *note = cJSON_GetObjectItem(periph_obj, "note");
    if (note && cJSON_IsString(note))
        cJSON_AddStringToObject(resp, "note", note->valuestring);

    /* no_pins flag: skip pin output for purely internal peripherals (e.g. rtc) */
    cJSON *no_pins_item = cJSON_GetObjectItem(periph_obj, "no_pins");
    bool   no_pins      = (no_pins_item && cJSON_IsTrue(no_pins_item));

    /* Per-instance status if instances array is present */
    cJSON *instances = cJSON_GetObjectItem(periph_obj, "instances");
    if (instances && cJSON_IsArray(instances)) {
        cJSON *insts_obj = cJSON_CreateObject();
        cJSON *inst;
        cJSON_ArrayForEach(inst, instances) {
            if (!inst->valuestring) continue;

            cJSON *inst_info = cJSON_CreateObject();

            /* Check if this instance is occupied by any interface */
            const brd_iface_t *matched = NULL;
            for (int j = 0; j < s_model.n_ifaces; j++) {
                if (str_icmp(s_model.ifaces[j].instance, inst->valuestring) == 0) {
                    matched = &s_model.ifaces[j];
                    break;
                }
            }

            if (matched) {
                cJSON_AddStringToObject(inst_info, "status",    "occupied");
                cJSON_AddStringToObject(inst_info, "interface", matched->id);

                /* Find device using this interface */
                for (int k = 0; k < s_model.n_devices; k++) {
                    if (strcmp(s_model.devices[k].iface_id, matched->id) == 0) {
                        cJSON_AddStringToObject(inst_info, "device",
                                                s_model.devices[k].id);
                        break;
                    }
                }

                /* Copy interface config: pin assignments plus any other parameters
                 * (e.g. default_freq_khz), excluding structural fields id/type/instance. */
                cJSON *config = cJSON_CreateObject();
                cJSON *field  = matched->obj ? matched->obj->child : NULL;
                while (field) {
                    const char *fn = field->string;
                    if (fn && strcmp(fn, "id")       != 0
                           && strcmp(fn, "type")     != 0
                           && strcmp(fn, "instance") != 0) {
                        cJSON *cp = cJSON_Duplicate(field, 1);
                        if (cp) cJSON_AddItemToObject(config, fn, cp);
                    }
                    field = field->next;
                }
                cJSON_AddItemToObject(inst_info, "config", config);
            } else {
                cJSON_AddStringToObject(inst_info, "status", "free");
            }

            cJSON_AddItemToObject(insts_obj, inst->valuestring, inst_info);
        }
        cJSON_AddItemToObject(resp, "instances", insts_obj);
    }

    /* Available pins (pre-computed at init, skipped for no-pin peripherals) */
    if (!no_pins) {
        cJSON *avail = cJSON_CreateArray();
        for (int i = 0; i < s_n_avail_pins; i++)
            cJSON_AddItemToArray(avail, cJSON_CreateString(s_avail_pins[i]));
        cJSON_AddItemToObject(resp, "available_pins", avail);
    }

    char *out = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);
    cJSON_Delete(req);
    if (!out) { *output = NULL; return RTK_ERR_NOMEM; }
    *output = out;
    return RTK_SUCCESS;
}

/* ---- board.reload: reload board from VFS ---- */

static int execute_board_reload(const char *input_json,
                                const claw_cap_call_context_t *ctx,
                                char **output)
{
    (void)input_json;
    (void)ctx;

    /* Re-init with the same VFS path used at startup.
     * Copy into a local buffer: cap_board_mgr_init calls memset(&s_model) which
     * would zero s_model.vfs_path while cfg.vfs_path still points into it. */
    char saved_path[64];
    strlcpy(saved_path,
            s_model.vfs_path[0] ? s_model.vfs_path : VFS_DEFAULT_PATH,
            sizeof(saved_path));
    cap_board_mgr_config_t cfg = { .vfs_path = saved_path };
    int rc = cap_board_mgr_init(&cfg);

    if (rc == RTK_SUCCESS) {
        cJSON *resp = cJSON_CreateObject();
        if (!resp) return RTK_ERR_NOMEM;
        cJSON_AddTrueToObject(resp, "success");
        cJSON_AddStringToObject(resp, "board", s_model.board_name);
        cJSON_AddNumberToObject(resp, "devices", s_model.n_devices);
        cJSON_AddNumberToObject(resp, "interfaces", s_model.n_ifaces);
        char *out = cJSON_PrintUnformatted(resp);
        cJSON_Delete(resp);
        if (!out) return RTK_ERR_NOMEM;
        *output = out;
        return RTK_SUCCESS;
    }
    return claw_cap_set_output(output, "{\"error\":\"board reload failed\"}");
}

/* ---- board.schema: return available chips, boards, and schema for LLM authoring ---- */

static const char *s_schema_authoring = ""
"{"
  "\"$schema\": \"board/authoring\","
  "\"description\": \"Authoring format for board.json. Fields with $ prefix are directives processed at load time and not stored.\","
  "\"fields\": {"
    "\"$chip\": {\"type\":\"string\",\"required\":true,\"description\":\"Chip name (e.g. RTL8721F). Determines chip_constraints from embedded chip database.\"},"
    "\"$extends\": {\"type\":\"string or null\",\"description\":\"Built-in board name to inherit from (e.g. EV721FL0_R03). null means no inheritance.\"},"
    "\"board\": {\"type\":\"object\",\"required\":true,\"fields\":{\"name\":{\"type\":\"string\",\"required\":true},\"chip\":{\"type\":\"string\",\"required\":true},\"description\":{\"type\":\"string\"}}},"
    "\"board_pins\": {\"type\":\"object\",\"fields\":{\"available\":{\"type\":\"array of strings\",\"description\":\"Pins physically broken out on this board\"},\"remove_pins\":{\"type\":\"array of strings\",\"description\":\"Pins to remove from the inherited base board's available list (only meaningful when $extends is set)\"}}},"
    "\"interfaces\": {\"type\":\"array\",\"items\":{\"type\":\"object\",\"fields\":{\"id\":{\"type\":\"string\",\"required\":true},\"type\":{\"type\":\"string\",\"required\":true},\"instance\":{\"type\":\"string\",\"required\":true},\"sda,scl,...\":{\"type\":\"string\",\"description\":\"Pin assignments per interface type\"}}}},"
    "\"devices\": {\"type\":\"array\",\"items\":{\"type\":\"object\",\"fields\":{"
      "\"$op\":{\"type\":\"string\",\"enum\":[\"remove\"],\"description\":\"remove this device from inherited base\"},"
      "\"id\":{\"type\":\"string\",\"required\":true},\"name\":{\"type\":\"string\"},\"type\":{\"type\":\"string\"},\"chip\":{\"type\":\"string\"},\"interface\":{\"type\":\"string\"},\"params\":{\"type\":\"object\"},\"lua_module\":{\"type\":\"string\"},\"notes\":{\"type\":\"string\"}"
    "}}}}"
  "}"
"}";

static int execute_board_schema(const char *input_json,
                                const claw_cap_call_context_t *ctx,
                                char **output)
{
    (void)input_json;
    (void)ctx;

    cJSON *resp = cJSON_CreateObject();
    if (!resp) return RTK_ERR_NOMEM;

    /* Available chips */
    cJSON *chips_arr = cJSON_CreateArray();
    for (int i = 0; s_chips[i].name; i++)
        cJSON_AddItemToArray(chips_arr, cJSON_CreateString(s_chips[i].name));
    cJSON_AddItemToObject(resp, "chips", chips_arr);

    /* Available built-in boards (for $extends) */
    cJSON *boards_arr = cJSON_CreateArray();
    for (int i = 0; s_boards[i].name; i++)
        cJSON_AddItemToArray(boards_arr, cJSON_CreateString(s_boards[i].name));
    cJSON_AddItemToObject(resp, "builtin_boards", boards_arr);

    /* Chip constraints detail for all supported chips */
    cJSON *all_chip_info = cJSON_CreateObject();
    if (all_chip_info) {
        for (int i = 0; s_chips[i].name; i++) {
            char *chip_str = load_embedded_res(s_chips, s_chips[i].name);
            if (chip_str) {
                cJSON *chip_json = cJSON_Parse(chip_str);
                if (chip_json)
                    cJSON_AddItemToObject(all_chip_info, s_chips[i].name, chip_json);
                rtos_mem_free(chip_str);
            }
        }
        cJSON_AddItemToObject(resp, "chip_info", all_chip_info);
    }

    /* Authoring schema */
    cJSON *schema = cJSON_Parse(s_schema_authoring);
    if (schema)
        cJSON_AddItemToObject(resp, "authoring_schema", schema);

    /* If board is already loaded, include current board info */
    if (s_model.loaded) {
        cJSON_AddStringToObject(resp, "current_board", s_model.board_name);
    }

    char *out = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);
    if (!out) { *output = NULL; return RTK_ERR_NOMEM; }
    *output = out;
    return RTK_SUCCESS;
}

/* ---- Context provider: compact board summary injected into system prompt ---- */

static int board_context_collect(const claw_agent_request_t *request,
                                 claw_agent_context_t *out_context,
                                 void *user_ctx)
{
    (void)request;
    (void)user_ctx;

    if (!s_model.loaded) return RTK_FAIL;

    /* Estimate required buffer size.
     * Device entry: " id(chip/type/iface_id)" — max fields 32+32+32+32 + 6 punctuation = 134
     * Interface entry: " id(instance/type)" — max fields 32+16+16 + 5 = 69
     */
    size_t need = 128
        + (size_t)s_model.n_devices * 144
        + (size_t)s_model.n_ifaces * 80
        + 128;

    char *buf = (char *)rtos_mem_malloc(need);
    if (!buf) return RTK_FAIL;

    int  pos = 0;

    pos += snprintf(buf + pos, need - (size_t)pos,
                    "[Board: %s]\nDevices:", s_model.board_name);

    for (int i = 0; i < s_model.n_devices; i++) {
        brd_device_t *d = &s_model.devices[i];
        int room = (int)need - pos;
        if (room < 4) {
            RTK_LOGW(TAG, "board_context_collect: buffer truncated at device %d/%d\n",
                     i, s_model.n_devices);
            break;
        }
        pos += snprintf(buf + pos, (size_t)room,
                        " %s(%s/%s/%s)", d->id, d->chip, d->type, d->iface_id);
    }

    pos += snprintf(buf + pos, need - (size_t)pos, "\nInterfaces:");
    for (int j = 0; j < s_model.n_ifaces; j++) {
        brd_iface_t *bi = &s_model.ifaces[j];
        int room = (int)need - pos;
        if (room < 4) {
            RTK_LOGW(TAG, "board_context_collect: buffer truncated at interface %d/%d\n",
                     j, s_model.n_ifaces);
            break;
        }
        pos += snprintf(buf + pos, (size_t)room,
                        " %s(%s/%s)", bi->id, bi->instance, bi->type);
    }

    pos += snprintf(buf + pos, need - (size_t)pos,
                    "\nFor a known device call board_get_device(id). "
                    "To use a peripheral (spi/uart/pwm/...) call board_query_peripheral(type).");

    /* Trim to actual size */
    char *content = rtos_mem_malloc((size_t)(pos + 1));
    if (!content) { rtos_mem_free(buf); return RTK_FAIL; }
    memcpy(content, buf, (size_t)(pos + 1));
    rtos_mem_free(buf);

    out_context->kind    = CLAW_AGENT_CONTEXT_KIND_SYSTEM_PROMPT;
    out_context->content = content;
    return RTK_SUCCESS;
}

const claw_agent_context_provider_t cap_board_mgr_context_provider = {
    .name     = "board",
    .collect  = board_context_collect,
    .user_ctx = NULL,
};

/* ---- Cap group registration ---- */

static const claw_cap_descriptor_t s_caps[] = {
    {
        .id          = "board_list_devices",
        .name        = "board_list_devices",
        .family      = "board",
        .description = "List all devices on the board with summary info (id, name, type, chip, interface id). "
                       "Does NOT include pin assignments or driver params — call board_get_device(id) for those.",
        .kind        = CLAW_CAP_KIND_INVOKE,
        .cap_flags   = CLAW_CAP_FLAG_LLM_ACCESS,
        .input_schema_json = "{\"type\":\"object\",\"properties\":{}}",
        .execute     = execute_board_list_devices,
    },
    {
        .id          = "board_get_device",
        .name        = "board_get_device",
        .family      = "board",
        .description = "Get full details for one board device by id: chip, interface pin assignments (sda/scl/etc.), "
                       "driver params (address, resolution, offsets), notes, and usage_guide. "
                       "Always call this before writing driver or Lua code for a device.",
        .kind        = CLAW_CAP_KIND_INVOKE,
        .cap_flags   = CLAW_CAP_FLAG_LLM_ACCESS,
        .input_schema_json =
            "{\"type\":\"object\","
            "\"properties\":{\"id\":{\"type\":\"string\","
            "\"description\":\"Device id from board_list_devices, e.g. \\\"oled\\\"\"}},"
            "\"required\":[\"id\"]}",
        .execute     = execute_board_get_device,
    },
    {
        .id          = "board_query_peripheral",
        .name        = "board_query_peripheral",
        .family      = "board",
        .description = "Query whether a peripheral is supported and which pins/instances are available. "
                       "Pass the peripheral type: i2c, spi, uart, adc, pwm, gpio, ir, audio, rtc. "
                       "Instance names (SPI0, UART1, TIM4 ...) are also accepted and resolve to their type. "
                       "Response includes: supported flag, per-instance status (free/occupied with pins), "
                       "and available_pins listing all physically broken-out board pins (board-available minus chip-reserved). "
                       "NOTE: available_pins includes pins already occupied by interfaces — check the instances section "
                       "to see which pins are in use before picking new pin assignments. "
                       "Returns {\"supported\":false} when the peripheral is not supported by this chip.",
        .kind        = CLAW_CAP_KIND_INVOKE,
        .cap_flags   = CLAW_CAP_FLAG_LLM_ACCESS,
        .input_schema_json =
            "{\"type\":\"object\","
            "\"properties\":{\"peripheral\":{\"type\":\"string\","
            "\"description\":\"Peripheral type (i2c/spi/uart/adc/pwm/gpio/ir/audio/rtc) "
            "or instance name (SPI0, UART2, TIM5 ...)\"}},"
            "\"required\":[\"peripheral\"]}",
        .execute     = execute_board_query_peripheral,
    },
    {
        .id          = "board_schema",
        .name        = "board_schema",
        .family      = "board",
        .description = "Get the board authoring schema: available chips, built-in boards for $extends, chip constraints "
                       "(pin reservations, peripheral instances), and the authoring JSON field definitions. "
                       "Use this to generate a custom board.json in authoring format with $chip and $extends directives. "
                       "The generated JSON can be written to vfs:/board.json and loaded via board.reload or restart.",
        .kind        = CLAW_CAP_KIND_INVOKE,
        .cap_flags   = CLAW_CAP_FLAG_LLM_ACCESS,
        .input_schema_json = "{\"type\":\"object\",\"properties\":{}}",
        .execute     = execute_board_schema,
    },
    {
        .id          = "board_reload",
        .name        = "board_reload",
        .family      = "board",
        .description = "Reload board configuration from VFS (vfs:/board.json). Use after writing a new board.json "
                       "to apply changes without rebooting. Returns the new board name, device count, and interface count.",
        .kind        = CLAW_CAP_KIND_INVOKE,
        .cap_flags   = CLAW_CAP_FLAG_LLM_ACCESS,
        .input_schema_json = "{\"type\":\"object\",\"properties\":{}}",
        .execute     = execute_board_reload,
    },
};

static const claw_cap_group_t s_group = {
    .group_id         = "board",
    .plugin_name      = "cap_board_mgr",
    .version          = "1",
    .descriptors      = s_caps,
    .descriptor_count = 5,
};

/* ---- Init ---- */

int cap_board_mgr_init(const cap_board_mgr_config_t *config)
{
    if (s_model.loaded) {
        cJSON_Delete(s_model.root);
        memset(&s_model, 0, sizeof(s_model));
    }

    const char *vfs_path = (config && config->vfs_path) ? config->vfs_path : VFS_DEFAULT_PATH;
    strlcpy(s_model.vfs_path, vfs_path, sizeof(s_model.vfs_path));

    (void)write_vfs_file;

    char *json_str = read_vfs_file(vfs_path);
    if (!json_str) {
        RTK_LOGI(TAG, "[board_mgr] VFS file missing, loading default board: %s\n",
                 CLAW_DEFAULT_BOARD_NAME);
        json_str = load_embedded_res(s_boards, CLAW_DEFAULT_BOARD_NAME);
        if (json_str && !write_vfs_file(vfs_path, json_str)) {
            RTK_LOGE(TAG, "[board_mgr] Failed to write embedded board JSON to VFS\n");
        }
    }

    if (!json_str) {
        RTK_LOGE(TAG, "[board_mgr] Failed to load board JSON\n");
        return RTK_FAIL;
    }

    cJSON *root = cJSON_Parse(json_str);
    rtos_mem_free(json_str);

    if (!root) {
        RTK_LOGE(TAG, "[board_mgr] Failed to parse board JSON\n");
        return RTK_FAIL;
    }

    /* Resolve $chip / $extends directives (runtime merge) */
    cJSON *resolved = board_resolve(root);
    if (resolved) {
        cJSON_Delete(root);
        root = resolved;
        RTK_LOGI(TAG, "[board_mgr] Board merge resolved\n");
    } else {
        /* Fall through with original root if merge fails */
        RTK_LOGE(TAG, "[board_mgr] Board merge failed, using raw JSON\n");
    }

    if (!build_model(root)) {
        cJSON_Delete(root);
        RTK_LOGE(TAG, "[board_mgr] Failed to build board model\n");
        return RTK_FAIL;
    }

    if (!s_group_registered) {
        claw_cap_register_group(&s_group);
        s_group_registered = true;
    }
    RTK_LOGI(TAG, "[board_mgr] Loaded: %s (%d devices, %d ifaces)\n",
             s_model.board_name, s_model.n_devices, s_model.n_ifaces);
    return RTK_SUCCESS;
}
