/* Auto-generated from test_lcdc_rgb_st7701p_touch_gt711.lua -- do not edit */
static const char s_lcdc_rgb_st7701p_touch_gt711_script[] =
    "-- test_lcdc_rgb_st7701p_touch_gt711.lua\n"
    "-- LCDC RGB888 480x480 (ST7701P) + GT911 capacitive touch test\n"
    "--\n"
    "-- Trigger: AT+CLAW=lcdc,rgb,st7701p\n"
    "--\n"
    "-- Precondition (provided by lua_lcdc_test_provision.c before this script runs):\n"
    "--   _lcdc_fb_addr   framebuffer base address (480x480 RGB888, carved from PSRAM top)\n"
    "--   gt911_poll()    C function: returns nil | {x=n, y=n, pressed=bool}\n"
    "--   fill_color, fill_rect, set_pixel   C pixel helpers (standard)\n"
    "--   SPI register init sequence already sent (panel_st7701p_rgb_spi.inc in C)\n"
    "--\n"
    "-- Requires: lcdc, gpio, sys\n"
    "--\n"
    "-- Pin encoding (RTL8721F): PA_X = X, PB_X = 0x20+X, PC_X = 0x40+X\n"
    "\n"
    "local lcdc = require('lcdc')\n"
    "local gpio = require('gpio')\n"
    "local sys  = require('sys')\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Board configuration: st7701p_rgb_480x480 / RTL8721F eval board\n"
    "-- (panel_pin_config.c — \"st7701p_rgb_480x480\" entry)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local fb_addr = _lcdc_fb_addr\n"
    "\n"
    "-- GPIO (SPI init + panel reset done in C; only BL needed here)\n"
    "local PIN_RESET = 0x17   -- PA_23  panel reset (already toggled in C)\n"
    "local PIN_BL    = 0x19   -- PA_25  backlight, active high\n"
    "\n"
    "-- LCDC configuration\n"
    "local PANEL_CFG = {\n"
    "    fb_addr      = fb_addr,\n"
    "    width        = 480,\n"
    "    height       = 480,\n"
    "    -- Timing from panel_st7701p_rgb.c panel_timing_t\n"
    "    vsw          = 3,\n"
    "    vbp          = 12,\n"
    "    vfp          = 15,\n"
    "    hsw          = 2,\n"
    "    hbp          = 2,\n"
    "    hfp          = 15,\n"
    "    refresh_freq = 60,\n"
    "    -- Format: RGB888 framebuffer → RGB888 output on 24-bit bus\n"
    "    input_fmt    = 'rgb888',\n"
    "    output_fmt   = 'rgb888',\n"
    "    if_width     = '24bit',\n"
    "    -- Polarity (from panel_timing_t)\n"
    "    en_pol       = 1,   -- DE active high   (de_active_high  = true)\n"
    "    hs_pol       = 0,   -- HSYNC active low (hsync_active_low = true)\n"
    "    vs_pol       = 0,   -- VSYNC active low (vsync_active_low = true)\n"
    "    dclk_edge    = 0,   -- rising edge      (dclk_falling_edge = false)\n"
    "}\n"
    "\n"
    "-- Pinmux (from panel_pin_config.c \"st7701p_rgb_480x480\")\n"
    "local PINMUX_CFG = {\n"
    "    -- RGB888 24-bit data bus D0–D23\n"
    "    d0  = 0x10,  d1  = 0x0F,  d2  = 0x0E,  d3  = 0x0D,  -- PA16,PA15,PA14,PA13\n"
    "    d4  = 0x0C,  d5  = 0x41,  d6  = 0x40,  d7  = 0x3F,  -- PA12,PC1, PC0, PB31\n"
    "    d8  = 0x3E,  d9  = 0x3D,  d10 = 0x3C,  d11 = 0x3B,  -- PB30,PB29,PB28,PB27\n"
    "    d12 = 0x3A,  d13 = 0x39,  d14 = 0x38,  d15 = 0x37,  -- PB26,PB25,PB24,PB23\n"
    "    d16 = 0x36,  d17 = 0x35,  d18 = 0x33,  d19 = 0x32,  -- PB22,PB21,PB19,PB18\n"
    "    d20 = 0x31,  d21 = 0x30,  d22 = 0x2F,  d23 = 0x2E,  -- PB17,PB16,PB15,PB14\n"
    "    -- Sync / timing signals\n"
    "    hsync = 0x13,  -- PA19\n"
    "    vsync = 0x12,  -- PA18\n"
    "    dclk  = 0x2D,  -- PB13\n"
    "    de    = 0x11,  -- PA17\n"
    "}\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Helpers\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local W, H = 480, 480\n"
    "\n"
    "local function show(label, ms)\n"
    "    sys.sleep_ms(20)   -- wait ~1 frame (17 ms at 60 Hz) before shadow reload\n"
    "    lcdc.update()\n"
    "    print(label)\n"
    "    sys.sleep_ms(ms)\n"
    "end\n"
    "\n"
    "-- Standard colour palette (RGB888)\n"
    "local R   = {255,   0,   0}\n"
    "local G   = {  0, 255,   0}\n"
    "local B   = {  0,   0, 255}\n"
    "local C   = {  0, 255, 255}\n"
    "local M   = {255,   0, 255}\n"
    "local Y   = {255, 255,   0}\n"
    "local WHT = {255, 255, 255}\n"
    "local BLK = {  0,   0,   0}\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Hardware init\n"
    "-- (SPI register sequence and panel reset were done in C)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "print(string.format('[st7701p] fb_addr = 0x%08X', fb_addr))\n"
    "\n"
    "gpio.set_direction(PIN_BL, 'output')\n"
    "gpio.set_level(PIN_BL, 0)\n"
    "\n"
    "lcdc.pinmux(PINMUX_CFG)\n"
    "\n"
    "print('[st7701p] rgb_init 480x480 RGB888')\n"
    "local ok, err = pcall(function()\n"
    "    if not lcdc.rgb_init(PANEL_CFG) then error('rgb_init returned false') end\n"
    "end)\n"
    "if not ok then\n"
    "    print('[st7701p] init FAILED: ' .. tostring(err))\n"
    "    gpio.set_level(PIN_BL, 0)\n"
    "    return\n"
    "end\n"
    "\n"
    "gpio.set_level(PIN_BL, 1)\n"
    "print('[st7701p] backlight ON')\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 1: solid colours  (2 s each)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(255, 0, 0)   show('[st7701p] p1 solid red',   2000)\n"
    "fill_color(0, 255, 0)   show('[st7701p] p1 solid green', 2000)\n"
    "fill_color(0, 0, 255)   show('[st7701p] p1 solid blue',  2000)\n"
    "fill_color(255,255,255) show('[st7701p] p1 solid white', 1500)\n"
    "fill_color(0,   0,   0) show('[st7701p] p1 solid black', 1500)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 2: horizontal stripes  8 bands × 60 px  (3 s)\n"
    "-- R / WHT / G / WHT / B / WHT / Y / WHT\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local hpal = {R, WHT, G, WHT, B, WHT, Y, WHT}\n"
    "for i, c in ipairs(hpal) do\n"
    "    fill_rect(0, (i-1)*60, W, 60, c[1], c[2], c[3])\n"
    "end\n"
    "show('[st7701p] p2 horizontal stripes (8x60px)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 3: SMPTE vertical colour bars  8 bands × 60 px  (3 s)\n"
    "-- WHT / Y / C / G / M / R / B / BLK\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local smpte = {WHT, Y, C, G, M, R, B, BLK}\n"
    "for i, c in ipairs(smpte) do\n"
    "    fill_rect((i-1)*60, 0, 60, H, c[1], c[2], c[3])\n"
    "end\n"
    "show('[st7701p] p3 SMPTE colour bars (8x60px)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 4: checkerboard  8×8 grid, 60×60 px cells  (3 s)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(0, 0, 0)\n"
    "for row = 0, 7 do\n"
    "    for col = 0, 7 do\n"
    "        if (row + col) % 2 == 0 then\n"
    "            fill_rect(col*60, row*60, 60, 60, 255, 255, 255)\n"
    "        end\n"
    "    end\n"
    "end\n"
    "show('[st7701p] p4 checkerboard 8x8', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 5: crosshatch grid  (3 s)\n"
    "-- black background + white lines every 60 px\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(0, 0, 0)\n"
    "for y = 60, 420, 60 do\n"
    "    fill_rect(0, y, W, 2, 255, 255, 255)\n"
    "end\n"
    "for x = 60, 420, 60 do\n"
    "    fill_rect(x, 0, 2, H, 255, 255, 255)\n"
    "end\n"
    "show('[st7701p] p5 crosshatch grid (60px spacing)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 6: RGB gradient bands  (3 s)\n"
    "-- top 160 px: R sweep 0→255, middle: G sweep, bottom: B sweep\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "for x = 0, W-1 do\n"
    "    local v = math.floor(x * 255 / (W - 1))\n"
    "    fill_rect(x,   0, 1, 160, v, 0, 0)\n"
    "    fill_rect(x, 160, 1, 160, 0, v, 0)\n"
    "    fill_rect(x, 320, 1, 160, 0, 0, v)\n"
    "end\n"
    "show('[st7701p] p6 RGB gradient bands', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- GT911 touch test  (15 seconds)\n"
    "-- Dark background; each tap draws a 20×20 orange marker.\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local TOUCH_ITERS = 750   -- 750 × 20 ms = 15 s\n"
    "local MARKER      = 20\n"
    "local tap_count   = 0\n"
    "local last_press  = false\n"
    "\n"
    "fill_color(20, 20, 50)\n"
    "fill_rect(0, 0, W, 32, 50, 50, 120)   -- title bar\n"
    "show('[st7701p] touch test — tap the screen (15 s)', 0)\n"
    "\n"
    "for _ = 1, TOUCH_ITERS do\n"
    "    local pt = gt911_poll()\n"
    "    if pt then\n"
    "        if pt.pressed and not last_press then\n"
    "            tap_count = tap_count + 1\n"
    "            local mx = math.max(0, math.min(W - MARKER, pt.x - MARKER // 2))\n"
    "            local my = math.max(32, math.min(H - MARKER, pt.y - MARKER // 2))\n"
    "            -- white border then orange fill\n"
    "            fill_rect(mx,   my,   MARKER,   MARKER,   255, 255, 255)\n"
    "            fill_rect(mx+2, my+2, MARKER-4, MARKER-4, 255,  80,   0)\n"
    "            lcdc.update()\n"
    "            print(string.format('[st7701p] tap#%d  x=%-3d y=%-3d',\n"
    "                                tap_count, pt.x, pt.y))\n"
    "        end\n"
    "        last_press = pt.pressed\n"
    "    end\n"
    "    sys.sleep_ms(20)\n"
    "end\n"
    "\n"
    "print(string.format('[st7701p] touch test done: %d taps in 15 s', tap_count))\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Diagnostic readback + teardown\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local sync = lcdc.rgb_get_sync_status()\n"
    "print(string.format('[st7701p] sync hs=%d vs=%d', sync.hs, sync.vs))\n"
    "\n"
    "local info = lcdc.get_info()\n"
    "print(string.format('[st7701p] w=%d h=%d init=%s fb=0x%08X',\n"
    "                    info.width, info.height, tostring(info.initialized), info.fb_addr))\n"
    "\n"
    "lcdc.enable(false)     -- stop output first\n"
    "sys.sleep_ms(50)       -- let LCDC finish current frame before deinit\n"
    "lcdc.deinit()\n"
    "gpio.set_level(PIN_BL, 0)\n"
    "\n"
    "if tap_count > 0 then\n"
    "    print('[st7701p] touch verified — success')\n"
    "else\n"
    "    print('[st7701p] no taps detected (display OK; touch needs physical interaction)')\n"
    "end\n"
    "print('success')\n"
;
