/* Auto-generated from test_lcdc_rgb_st7262.lua -- do not edit */
static const char s_lcdc_rgb_st7262_script[] =
    "-- test_lcdc_rgb_st7262.lua\n"
    "-- LCDC RGB interface test: st7262 800x480 panel / RTL8721F eval board\n"
    "--\n"
    "-- Trigger: AT+CLAW=lcdc,rgb,st7262\n"
    "--\n"
    "-- Precondition (provided by lua_lcdc_test_provision.c):\n"
    "--   _lcdc_fb_addr  global integer, C code carves an RGB565 framebuffer from\n"
    "--                  PSRAM top and injects it via lua_setglobal().\n"
    "--\n"
    "-- Requires: lcdc, gpio, sys\n"
    "\n"
    "local lcdc = require('lcdc')\n"
    "local gpio = require('gpio')\n"
    "local sys  = require('sys')\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Board configuration: st7262 / RTL8721F eval board\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local fb_addr = _lcdc_fb_addr\n"
    "\n"
    "local PIN_BLEN = 0x23   -- PB_3  backlight, active high\n"
    "local PIN_DISP = 0x11   -- PA_17 display-on, active high\n"
    "\n"
    "local PANEL_CFG = {\n"
    "    fb_addr      = fb_addr,\n"
    "    width        = 800,\n"
    "    height       = 480,\n"
    "    vsw          = 1,\n"
    "    vbp          = 4,\n"
    "    vfp          = 6,\n"
    "    hsw          = 4,\n"
    "    hbp          = 40,\n"
    "    hfp          = 40,\n"
    "    refresh_freq = 40,\n"
    "    input_fmt    = 'rgb565',\n"
    "    output_fmt   = 'bgr888',\n"
    "    if_width     = '24bit',\n"
    "}\n"
    "\n"
    "local PINMUX_CFG = {\n"
    "    d0  = 0x2F,  d1  = 0x31,  d2  = 0x35,  d3  = 0x32,  -- PB15,PB17,PB21,PB18\n"
    "    d4  = 0x06,  d5  = 0x08,  d6  = 0x07,  d7  = 0x0A,  -- PA6, PA8, PA7, PA10\n"
    "    d8  = 0x29,  d9  = 0x2B,  d10 = 0x2A,  d11 = 0x30,  -- PB9, PB11,PB10,PB16\n"
    "    d12 = 0x36,  d13 = 0x37,  d14 = 0x2E,  d15 = 0x2C,  -- PB22,PB23,PB14,PB12\n"
    "    d16 = 0x16,  d17 = 0x19,  d18 = 0x1D,  d19 = 0x24,  -- PA22,PA25,PA29,PB4\n"
    "    d20 = 0x25,  d21 = 0x26,  d22 = 0x27,  d23 = 0x28,  -- PB5, PB6, PB7, PB8\n"
    "    hsync = 0x10,  vsync = 0x0D,  dclk = 0x09,  de = 0x0E,\n"
    "}\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Helpers\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local W, H = 800, 480\n"
    "\n"
    "-- Flush framebuffer to screen and hold for ms milliseconds\n"
    "local function show(label, ms)\n"
    "    lcdc.update()\n"
    "    print(label)\n"
    "    sys.sleep_ms(ms)\n"
    "end\n"
    "\n"
    "-- Color palette (RGB888)\n"
    "local R   = {255,   0,   0}\n"
    "local G   = {  0, 255,   0}\n"
    "local B   = {  0,   0, 255}\n"
    "local C   = {  0, 255, 255}\n"
    "local M   = {255,   0, 255}\n"
    "local Y   = {255, 255,   0}\n"
    "local WHT = {255, 255, 255}\n"
    "local BLK = {  0,   0,   0}\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Hardware init\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "print(string.format('[lcdc rgb] fb_addr = 0x%08X', fb_addr))\n"
    "\n"
    "gpio.set_direction(PIN_BLEN, 'output') gpio.set_level(PIN_BLEN, 1)\n"
    "gpio.set_direction(PIN_DISP, 'output') gpio.set_level(PIN_DISP, 1)\n"
    "\n"
    "lcdc.pinmux(PINMUX_CFG)\n"
    "\n"
    "print('[lcdc rgb] init st7262 800x480')\n"
    "local ok, err = pcall(function()\n"
    "    if not lcdc.rgb_init(PANEL_CFG) then error('rgb_init returned false') end\n"
    "end)\n"
    "if not ok then\n"
    "    print('[lcdc rgb] init failed: ' .. tostring(err))\n"
    "    gpio.set_level(PIN_BLEN, 0) gpio.set_level(PIN_DISP, 0)\n"
    "    return\n"
    "end\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 1: solid colours (3 s each)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(255, 0, 0)   show('[rgb] p1 solid red',   3000)\n"
    "fill_color(0, 255, 0)   show('[rgb] p1 solid green', 3000)\n"
    "fill_color(0, 0, 255)   show('[rgb] p1 solid blue',  3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 2: horizontal stripes (8 bands × 60 px, 3 s)\n"
    "-- R / white / G / white / B / white / Y / white\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local hpal = {R, WHT, G, WHT, B, WHT, Y, WHT}\n"
    "for i, c in ipairs(hpal) do\n"
    "    fill_rect(0, (i-1)*60, W, 60, c[1], c[2], c[3])\n"
    "end\n"
    "show('[rgb] p2 horizontal stripes (8x60px)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 3: vertical stripes (8 bands × 100 px, 3 s)\n"
    "-- R / G / B / C / M / Y / white / black\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local vpal = {R, G, B, C, M, Y, WHT, BLK}\n"
    "for i, c in ipairs(vpal) do\n"
    "    fill_rect((i-1)*100, 0, 100, H, c[1], c[2], c[3])\n"
    "end\n"
    "show('[rgb] p3 vertical stripes (8x100px)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 4: checkerboard (8 cols × 8 rows, 100×60 px cells, 3 s)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(0, 0, 0)\n"
    "for row = 0, 7 do\n"
    "    for col = 0, 7 do\n"
    "        if (row + col) % 2 == 0 then\n"
    "            fill_rect(col*100, row*60, 100, 60, 255, 255, 255)\n"
    "        end\n"
    "    end\n"
    "end\n"
    "show('[rgb] p4 checkerboard (8x8 cells)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 5: SMPTE colour bars (8 vertical bars × 100 px, 3 s)\n"
    "-- white / yellow / cyan / green / magenta / red / blue / black\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local smpte = {WHT, Y, C, G, M, R, B, BLK}\n"
    "for i, c in ipairs(smpte) do\n"
    "    fill_rect((i-1)*100, 0, 100, H, c[1], c[2], c[3])\n"
    "end\n"
    "show('[rgb] p5 SMPTE colour bars', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 6: crosshatch grid (black bg + white lines, 3 s)\n"
    "-- horizontal lines every 60 px, vertical lines every 100 px\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(0, 0, 0)\n"
    "for y = 60, 420, 60 do\n"
    "    fill_rect(0, y, W, 2, 255, 255, 255)\n"
    "end\n"
    "for x = 100, 700, 100 do\n"
    "    fill_rect(x, 0, 2, H, 255, 255, 255)\n"
    "end\n"
    "show('[rgb] p6 crosshatch grid', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Status and teardown\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local sync = lcdc.rgb_get_sync_status()\n"
    "print(string.format('[lcdc rgb] sync hs=%d vs=%d', sync.hs, sync.vs))\n"
    "\n"
    "local info = lcdc.get_info()\n"
    "print(string.format('[lcdc rgb] w=%d h=%d init=%s fb=0x%08X',\n"
    "    info.width, info.height, tostring(info.initialized), info.fb_addr))\n"
    "\n"
    "lcdc.deinit()\n"
    "gpio.set_level(PIN_BLEN, 0) gpio.set_level(PIN_DISP, 0)\n"
    "\n"
    "print('success')\n"
;
