/* Auto-generated from test_lcdc_srgb_st7272a.lua -- do not edit */
static const char s_lcdc_srgb_st7272a_script[] =
    "-- test_lcdc_srgb_st7272a.lua\n"
    "-- LCDC SRGB (8-bit serial RGB) interface test: ST7272A 320x240 panel\n"
    "--\n"
    "-- Trigger: AT+CLAW=lcdc,srgb,st7272a\n"
    "--\n"
    "-- Precondition (provided by lua_lcdc_test_provision.c):\n"
    "--   _lcdc_fb_addr  global integer, C code carves an RGB888 framebuffer from\n"
    "--                  PSRAM top and injects it via lua_setglobal().\n"
    "--\n"
    "-- Pin reference: example/peripheral/raw/Display/LCDC/raw_lcdc_srgb_st7272a/\n"
    "--   example_raw_lcdc_srgb_st7272a.c\n"
    "--\n"
    "-- Requires: lcdc, gpio, sys\n"
    "\n"
    "local lcdc = require('lcdc')\n"
    "local gpio = require('gpio')\n"
    "local sys  = require('sys')\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Board configuration: pins from example_raw_lcdc_srgb_st7272a.c\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local fb_addr = _lcdc_fb_addr\n"
    "\n"
    "local PIN_BLEN  = 0x23   -- PB_3  backlight, active high\n"
    "local PIN_RESET = 0x36   -- PB_22 reset, active high\n"
    "\n"
    "local PINMUX_CFG = {\n"
    "    d0=0x06, d1=0x08, d2=0x07, d3=0x0A,   -- PA6,PA8,PA7,PA10\n"
    "    d4=0x0B, d5=0x09, d6=0x11, d7=0x10,   -- PA11,PA9,PA17,PA16\n"
    "    hsync=0x35, vsync=0x31, dclk=0x2E, de=0x0E,\n"
    "}\n"
    "\n"
    "local PANEL_CFG = {\n"
    "    fb_addr=fb_addr, width=320, height=240,\n"
    "    if_width='8bit', input_fmt='rgb888', output_fmt='bgr888',\n"
    "    vsw=4, vbp=8, vfp=8, hsw=4, hbp=39, hfp=8, refresh_freq=35,\n"
    "    en_pol=1, hs_pol=0, vs_pol=0, dclk_edge=1,\n"
    "}\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Helpers\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local W, H = 320, 240\n"
    "\n"
    "-- Flush framebuffer to screen and hold for ms milliseconds\n"
    "local function show(label, ms)\n"
    "    lcdc.update()\n"
    "    print(label)\n"
    "    sys.sleep_ms(ms)\n"
    "end\n"
    "\n"
    "-- Color palette (RGB888)\n"
    "local R   = {255,   0,   0}\n"
    "local G   = {  0, 255,   0}\n"
    "local B   = {  0,   0, 255}\n"
    "local C   = {  0, 255, 255}\n"
    "local M   = {255,   0, 255}\n"
    "local Y   = {255, 255,   0}\n"
    "local WHT = {255, 255, 255}\n"
    "local BLK = {  0,   0,   0}\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Hardware init\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "print(string.format('[lcdc srgb] fb_addr = 0x%08X', fb_addr))\n"
    "\n"
    "gpio.set_direction(PIN_RESET, 'output')\n"
    "gpio.set_level(PIN_RESET, 1)\n"
    "sys.sleep_ms(100)\n"
    "\n"
    "gpio.set_direction(PIN_BLEN, 'output')\n"
    "gpio.set_level(PIN_BLEN, 1)\n"
    "\n"
    "lcdc.pinmux(PINMUX_CFG)\n"
    "\n"
    "print('[lcdc srgb] init (8-bit, 320x240, 35Hz)')\n"
    "local ok, err = pcall(function()\n"
    "    if not lcdc.rgb_init(PANEL_CFG) then error('rgb_init returned false') end\n"
    "end)\n"
    "if not ok then\n"
    "    print('[lcdc srgb] init failed: ' .. tostring(err))\n"
    "    gpio.set_level(PIN_BLEN, 0)\n"
    "    return\n"
    "end\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 1: solid colours (3 s each)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(255, 0, 0)   show('[srgb] p1 solid red',   3000)\n"
    "fill_color(0, 255, 0)   show('[srgb] p1 solid green', 3000)\n"
    "fill_color(0, 0, 255)   show('[srgb] p1 solid blue',  3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 2: horizontal stripes (8 bands × 30 px, 3 s)\n"
    "-- R / white / G / white / B / white / Y / white\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local hpal = {R, WHT, G, WHT, B, WHT, Y, WHT}\n"
    "for i, c in ipairs(hpal) do\n"
    "    fill_rect(0, (i-1)*30, W, 30, c[1], c[2], c[3])\n"
    "end\n"
    "show('[srgb] p2 horizontal stripes (8x30px)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 3: vertical stripes (8 bands × 40 px, 3 s)\n"
    "-- R / G / B / C / M / Y / white / black\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local vpal = {R, G, B, C, M, Y, WHT, BLK}\n"
    "for i, c in ipairs(vpal) do\n"
    "    fill_rect((i-1)*40, 0, 40, H, c[1], c[2], c[3])\n"
    "end\n"
    "show('[srgb] p3 vertical stripes (8x40px)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 4: checkerboard (8 cols × 8 rows, 40×30 px cells, 3 s)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(0, 0, 0)\n"
    "for row = 0, 7 do\n"
    "    for col = 0, 7 do\n"
    "        if (row + col) % 2 == 0 then\n"
    "            fill_rect(col*40, row*30, 40, 30, 255, 255, 255)\n"
    "        end\n"
    "    end\n"
    "end\n"
    "show('[srgb] p4 checkerboard (8x8 cells)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 5: SMPTE colour bars (8 vertical bars × 40 px, 3 s)\n"
    "-- white / yellow / cyan / green / magenta / red / blue / black\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local smpte = {WHT, Y, C, G, M, R, B, BLK}\n"
    "for i, c in ipairs(smpte) do\n"
    "    fill_rect((i-1)*40, 0, 40, H, c[1], c[2], c[3])\n"
    "end\n"
    "show('[srgb] p5 SMPTE colour bars', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 6: crosshatch grid (black bg + white lines, 3 s)\n"
    "-- horizontal lines every 30 px, vertical lines every 40 px\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(0, 0, 0)\n"
    "for y = 30, 210, 30 do\n"
    "    fill_rect(0, y, W, 2, 255, 255, 255)\n"
    "end\n"
    "for x = 40, 280, 40 do\n"
    "    fill_rect(x, 0, 2, H, 255, 255, 255)\n"
    "end\n"
    "show('[srgb] p6 crosshatch grid', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Status and teardown\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local sync = lcdc.rgb_get_sync_status()\n"
    "print(string.format('[lcdc srgb] sync hs=%d vs=%d', sync.hs, sync.vs))\n"
    "\n"
    "local info = lcdc.get_info()\n"
    "print(string.format('[lcdc srgb] w=%d h=%d init=%s fb=0x%08X',\n"
    "    info.width, info.height, tostring(info.initialized), info.fb_addr))\n"
    "\n"
    "lcdc.deinit()\n"
    "gpio.set_level(PIN_BLEN, 0)\n"
    "\n"
    "print('success')\n"
;
