/* Auto-generated from test_lcdc_mcu_ili9806.lua -- do not edit */
static const char s_lcdc_mcu_ili9806_script[] =
    "-- test_lcdc_mcu_ili9806.lua\n"
    "-- LCDC MCU (8080 parallel) interface test: ILI9806 480x800 panel\n"
    "--\n"
    "-- Trigger: AT+CLAW=lcdc,mcu,ili9806\n"
    "--\n"
    "-- Precondition (provided by lua_lcdc_test_provision.c):\n"
    "--   _lcdc_fb_addr  global integer, C code carves an RGB888 framebuffer from\n"
    "--                  PSRAM top and injects it via lua_setglobal().\n"
    "--\n"
    "-- Pin reference: example/peripheral/raw/Display/LCDC/raw_lcdc_mcu_ili9806/\n"
    "--   example_raw_lcdc_mcu_ili9806.c  bsp_mcu_com.h  bsp_mcu_ili9806.h\n"
    "--\n"
    "-- Requires: lcdc, gpio, sys\n"
    "\n"
    "local lcdc = require('lcdc')\n"
    "local gpio = require('gpio')\n"
    "local sys  = require('sys')\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Board configuration: pins from example_raw_lcdc_mcu_ili9806.c\n"
    "--                      and bsp_mcu_ili9806.h\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local fb_addr = _lcdc_fb_addr\n"
    "\n"
    "-- Backlight (LCD_BLEN_MCU = PB_3 = 0x23), active high\n"
    "local PIN_BLEN = 0x23\n"
    "\n"
    "-- Panel reset (MCU_RESET_PIN = PA_8 = 0x08), active low\n"
    "local PIN_RST  = 0x08\n"
    "\n"
    "-- Interface mode select (IM[3:0] = 0010 -> 24-bit parallel)\n"
    "-- MCU_IM3_PIN=PA_14=0x0E  MCU_IM2_PIN=PA_13=0x0D\n"
    "-- MCU_IM1_PIN=PA_16=0x10  MCU_IM0_PIN=PA_17=0x11\n"
    "local PIN_IM3  = 0x0E   -- PA_14\n"
    "local PIN_IM2  = 0x0D   -- PA_13\n"
    "local PIN_IM1  = 0x10   -- PA_16\n"
    "local PIN_IM0  = 0x11   -- PA_17\n"
    "\n"
    "-- LCDC MCU signal pins (24-bit data bus + control)\n"
    "-- Source: lcdc_pinmux_config() in example_raw_lcdc_mcu_ili9806.c\n"
    "local PINMUX_CFG = {\n"
    "    -- Data bus D0-D23\n"
    "    d0  = 0x1A,  d1  = 0x18,  d2  = 0x17,  d3  = 0x16,  -- PA26,PA24,PA23,PA22\n"
    "    d4  = 0x19,  d5  = 0x1D,  d6  = 0x24,  d7  = 0x25,  -- PA25,PA29,PB4, PB5\n"
    "    d8  = 0x26,  d9  = 0x27,  d10 = 0x28,  d11 = 0x29,  -- PB6, PB7, PB8, PB9\n"
    "    d12 = 0x2B,  d13 = 0x2A,  d14 = 0x30,  d15 = 0x36,  -- PB11,PB10,PB16,PB22\n"
    "    d16 = 0x37,  d17 = 0x2E,  d18 = 0x2C,  d19 = 0x2F,  -- PB23,PB14,PB12,PB15\n"
    "    d20 = 0x31,  d21 = 0x35,  d22 = 0x32,  d23 = 0x06,  -- PB17,PB21,PB18,PA6\n"
    "    -- Control signals\n"
    "    dcx = 0x09,  -- PA_9  (LCD_MCU_DCX)\n"
    "    wr  = 0x0B,  -- PA_11 (LCD_MCU_WR)\n"
    "    rd  = 0x0A,  -- PA_10 (LCD_MCU_RD)\n"
    "    cs  = 0x07,  -- PA_7  (LCD_MCU_CSX)\n"
    "}\n"
    "\n"
    "-- ILI9806 LCDC init params (24-bit parallel, RGB888)\n"
    "local PANEL_CFG = {\n"
    "    width      = 480,\n"
    "    height     = 800,\n"
    "    if_width   = '24bit',\n"
    "    input_fmt  = 'rgb888',\n"
    "    output_fmt = 'rgb888',\n"
    "    wrpulw     = 1,\n"
    "    wr_pol     = 0,  -- LCDC_MCU_WR_PUL_RISING_EDGE_FETCH\n"
    "    rd_pol     = 0,  -- LCDC_MCU_RD_PUL_RISING_EDGE_FETCH\n"
    "    rs_pol     = 0,  -- LCDC_MCU_RS_PUL_LOW_LEV_CMD_ADDR\n"
    "    dma_burst  = 2,  -- LCDC_DMA_BURSTSIZE_4X64BYTES\n"
    "}\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- ILI9806 init sequence\n"
    "-- Source: ILI9806_Init() in bsp_mcu_ili9806.c\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local function wc(cmd)  lcdc.mcu_io_write_cmd(cmd)  end\n"
    "local function wd(data) lcdc.mcu_io_write_data(data) end\n"
    "\n"
    "local function ili9806_init()\n"
    "    wc(0xFF) wd(0xFF) wd(0x98) wd(0x06)   -- EXTC: unlock extended command set\n"
    "\n"
    "    -- GIP 1\n"
    "    wc(0xBC)\n"
    "    wd(0x01) wd(0x0F) wd(0x61) wd(0xFF) wd(0x01) wd(0x01) wd(0x0B) wd(0x10)\n"
    "    wd(0x37) wd(0x63) wd(0xFF) wd(0xFF) wd(0x01) wd(0x01) wd(0x00) wd(0x00)\n"
    "    wd(0xFF) wd(0x52) wd(0x01) wd(0x00) wd(0x40)\n"
    "\n"
    "    -- GIP 2\n"
    "    wc(0xBD)\n"
    "    wd(0x01) wd(0x23) wd(0x45) wd(0x67) wd(0x01) wd(0x23) wd(0x45) wd(0x67)\n"
    "\n"
    "    -- GIP 3\n"
    "    wc(0xBE)\n"
    "    wd(0x00) wd(0x01) wd(0xAB) wd(0x60) wd(0x22) wd(0x22) wd(0x22) wd(0x22) wd(0x22)\n"
    "\n"
    "    wc(0xC7) wd(0x36)                      -- VCOM control\n"
    "    wc(0xED) wd(0x7F) wd(0x0F)             -- EN_volt_reg\n"
    "    wc(0xC0) wd(0x0F) wd(0x0B) wd(0x0A)   -- Power control 1\n"
    "    wc(0xFC) wd(0x08)                      -- AVDD internal pumping\n"
    "    wc(0xDF) wd(0x00) wd(0x00) wd(0x00) wd(0x00) wd(0x00) wd(0x20)\n"
    "    wc(0xF3) wd(0x74)                      -- DVDD voltage\n"
    "    wc(0xB4) wd(0x00) wd(0x00) wd(0x00)   -- Inversion type\n"
    "    wc(0xF7) wd(0x82)                      -- Resolution control: 480x800\n"
    "    wc(0xB1) wd(0x00) wd(0x13) wd(0x13)   -- Frame rate\n"
    "    wc(0xF2) wd(0x80) wd(0x04) wd(0x40) wd(0x28)\n"
    "    wc(0xC1) wd(0x17) wd(0x88) wd(0x88) wd(0x20)  -- Power control 2\n"
    "\n"
    "    -- Positive gamma\n"
    "    wc(0xE0)\n"
    "    wd(0x00) wd(0x0A) wd(0x12) wd(0x10) wd(0x0E) wd(0x20) wd(0xCC) wd(0x07)\n"
    "    wd(0x06) wd(0x0B) wd(0x0E) wd(0x0F) wd(0x0D) wd(0x15) wd(0x10) wd(0x00)\n"
    "\n"
    "    -- Negative gamma\n"
    "    wc(0xE1)\n"
    "    wd(0x00) wd(0x0B) wd(0x13) wd(0x0D) wd(0x0E) wd(0x1B) wd(0x71) wd(0x06)\n"
    "    wd(0x06) wd(0x0A) wd(0x0F) wd(0x0E) wd(0x0F) wd(0x15) wd(0x0C) wd(0x00)\n"
    "\n"
    "    wc(0x2A) wd(0x00) wd(0x00) wd(0x01) wd(0xDF)  -- Column address set (0-479)\n"
    "    wc(0x2B) wd(0x00) wd(0x00) wd(0x03) wd(0x1F)  -- Row address set (0-799)\n"
    "    wc(0x3A) wd(0x77)                              -- Pixel format: 24bpp RGB888\n"
    "    wc(0x36) wd(0x00)                              -- Memory access control\n"
    "\n"
    "    wc(0x11)                                       -- Sleep out\n"
    "    sys.sleep_ms(120)\n"
    "    wc(0x29)                                       -- Display on\n"
    "    sys.sleep_ms(20)\n"
    "    wc(0x2C)                                       -- Memory write\n"
    "end\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Test body\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local W, H = 480, 800\n"
    "\n"
    "-- Flush framebuffer via DMA and hold for ms milliseconds\n"
    "local function show(label, ms)\n"
    "    lcdc.mcu_dma_trigger()\n"
    "    print(label)\n"
    "    sys.sleep_ms(ms)\n"
    "end\n"
    "\n"
    "-- Color palette (RGB888)\n"
    "local R   = {255,   0,   0}\n"
    "local G   = {  0, 255,   0}\n"
    "local B   = {  0,   0, 255}\n"
    "local C   = {  0, 255, 255}\n"
    "local M   = {255,   0, 255}\n"
    "local Y   = {255, 255,   0}\n"
    "local WHT = {255, 255, 255}\n"
    "local BLK = {  0,   0,   0}\n"
    "\n"
    "print(string.format('[lcdc mcu] fb_addr = 0x%08X', fb_addr))\n"
    "print('[lcdc mcu] configuring pins (ILI9806 / example_raw_lcdc_mcu_ili9806)')\n"
    "\n"
    "-- Backlight on: PB_3\n"
    "gpio.set_direction(PIN_BLEN, 'output')\n"
    "gpio.set_level(PIN_BLEN, 1)\n"
    "\n"
    "-- Reset: PA_8, high -> low(10ms) -> high, wait 120ms\n"
    "gpio.set_direction(PIN_RST, 'output')\n"
    "gpio.set_level(PIN_RST, 1)\n"
    "sys.sleep_ms(2)\n"
    "gpio.set_level(PIN_RST, 0)\n"
    "sys.sleep_ms(10)\n"
    "gpio.set_level(PIN_RST, 1)\n"
    "sys.sleep_ms(120)\n"
    "\n"
    "-- IM[3:0] = 0010 -> 24-bit parallel mode\n"
    "gpio.set_direction(PIN_IM3, 'output') gpio.set_level(PIN_IM3, 0)\n"
    "gpio.set_direction(PIN_IM2, 'output') gpio.set_level(PIN_IM2, 0)\n"
    "gpio.set_direction(PIN_IM1, 'output') gpio.set_level(PIN_IM1, 1)\n"
    "gpio.set_direction(PIN_IM0, 'output') gpio.set_level(PIN_IM0, 0)\n"
    "sys.sleep_ms(50)\n"
    "\n"
    "-- Configure LCDC signal pinmux\n"
    "lcdc.pinmux(PINMUX_CFG)\n"
    "\n"
    "-- Init LCDC MCU mode\n"
    "print('[lcdc mcu] init LCDC MCU mode')\n"
    "local ok, err = pcall(function()\n"
    "    local ret = lcdc.mcu_init(PANEL_CFG)\n"
    "    if not ret then error('mcu_init returned false') end\n"
    "end)\n"
    "if not ok then\n"
    "    print('[lcdc mcu] mcu_init failed: ' .. tostring(err))\n"
    "    gpio.set_level(PIN_BLEN, 0)\n"
    "    return\n"
    "end\n"
    "\n"
    "-- Send ILI9806 init sequence via IO mode\n"
    "print('[lcdc mcu] sending ILI9806 init sequence')\n"
    "ili9806_init()\n"
    "\n"
    "sys.sleep_ms(100)\n"
    "\n"
    "-- Confirm full-screen window before DMA (CASET 0..479, RASET 0..799)\n"
    "wc(0x2A) wd(0x00) wd(0x00) wd(0x01) wd(0xDF)\n"
    "wc(0x2B) wd(0x00) wd(0x00) wd(0x03) wd(0x1F)\n"
    "sys.sleep_ms(50)\n"
    "lcdc.mcu_set_pre_cmd(0x2C)\n"
    "lcdc.mcu_dma_start(fb_addr, 1, 2)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 1: solid colours (3 s each)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(255, 0, 0)   show('[mcu] p1 solid red',   3000)\n"
    "fill_color(0, 255, 0)   show('[mcu] p1 solid green', 3000)\n"
    "fill_color(0, 0, 255)   show('[mcu] p1 solid blue',  3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 2: horizontal stripes (8 bands × 100 px, 3 s)\n"
    "-- R / white / G / white / B / white / Y / white\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local hpal = {R, WHT, G, WHT, B, WHT, Y, WHT}\n"
    "for i, c in ipairs(hpal) do\n"
    "    fill_rect(0, (i-1)*100, W, 100, c[1], c[2], c[3])\n"
    "end\n"
    "show('[mcu] p2 horizontal stripes (8x100px)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 3: vertical stripes (8 bands × 60 px, 3 s)\n"
    "-- R / G / B / C / M / Y / white / black\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local vpal = {R, G, B, C, M, Y, WHT, BLK}\n"
    "for i, c in ipairs(vpal) do\n"
    "    fill_rect((i-1)*60, 0, 60, H, c[1], c[2], c[3])\n"
    "end\n"
    "show('[mcu] p3 vertical stripes (8x60px)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 4: checkerboard (8 cols × 8 rows, 60×100 px cells, 3 s)\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(0, 0, 0)\n"
    "for row = 0, 7 do\n"
    "    for col = 0, 7 do\n"
    "        if (row + col) % 2 == 0 then\n"
    "            fill_rect(col*60, row*100, 60, 100, 255, 255, 255)\n"
    "        end\n"
    "    end\n"
    "end\n"
    "show('[mcu] p4 checkerboard (8x8 cells)', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 5: SMPTE colour bars (8 vertical bars × 60 px, 3 s)\n"
    "-- white / yellow / cyan / green / magenta / red / blue / black\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local smpte = {WHT, Y, C, G, M, R, B, BLK}\n"
    "for i, c in ipairs(smpte) do\n"
    "    fill_rect((i-1)*60, 0, 60, H, c[1], c[2], c[3])\n"
    "end\n"
    "show('[mcu] p5 SMPTE colour bars', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Pattern 6: crosshatch grid (black bg + white lines, 3 s)\n"
    "-- horizontal lines every 100 px, vertical lines every 60 px\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "fill_color(0, 0, 0)\n"
    "for y = 100, 700, 100 do\n"
    "    fill_rect(0, y, W, 2, 255, 255, 255)\n"
    "end\n"
    "for x = 60, 420, 60 do\n"
    "    fill_rect(x, 0, 2, H, 255, 255, 255)\n"
    "end\n"
    "show('[mcu] p6 crosshatch grid', 3000)\n"
    "\n"
    "-- ----------------------------------------------------------------\n"
    "-- Status and teardown\n"
    "-- ----------------------------------------------------------------\n"
    "\n"
    "local status = lcdc.mcu_get_run_status()\n"
    "print(string.format('[lcdc mcu] run_status = 0x%08X', status))\n"
    "\n"
    "local info = lcdc.get_info()\n"
    "print(string.format('[lcdc mcu] width=%d height=%d initialized=%s fb_addr=0x%08X',\n"
    "    info.width, info.height, tostring(info.initialized), info.fb_addr))\n"
    "\n"
    "-- Teardown\n"
    "lcdc.deinit()\n"
    "gpio.set_level(PIN_BLEN, 0)\n"
    "\n"
    "print('success')\n"
;
