/*
 * Copyright (c) 2026 Realtek Semiconductor Corp.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#include "ameba_soc.h"
#include "ameba_claw_defs.h"
#include "wifi_api_types.h"   /* for RTW_ESSID_MAX_SIZE */
#include "cap_webui.h"
#include "claw_cap_registry.h"
#ifdef CONFIG_CLAW_CAP_IM_WECHAT
#include "cap_im_wechat.h"
#endif
#ifdef CONFIG_CLAW_CAP_IM_LOCAL
#include "cap_im_local.h"
#endif
#ifdef CONFIG_CLAW_CAP_SKILL_MGR
#include "cap_skill_mgr.h"
#endif
#include "claw_http_server.h"
#include "claw_config.h"
#include "lua_module_registry.h"
#include "claw_cap.h"
#include "claw_wifi_mgr.h"
#include "claw_compat.h"
#include "cap_session_mgr.h"
#include "claw_memory.h"
#include "os_wrapper_memory.h"
#include "os_wrapper.h"
#include "sys_api.h"
#include "vfs.h"
#include <cJSON.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/stat.h>
#include "lwip/sockets.h"

/* Resources generated by build_html.py and embedded via CMakeLists.txt */
extern const unsigned char _res_dashboard_html_start[];
extern const unsigned int  _res_dashboard_html_size;
extern const unsigned char _res_favicon_ico_start[];
extern const unsigned char _res_favicon_ico_end[];

#define TAG "cap_webui"

/* ---- Async provisioning connect ---------------------------------------- */
typedef struct {
    char ssid[64];
    char password[64];
    char security_type[16];
} prov_connect_args_t;

static void prov_connect_task(void *param)
{
    prov_connect_args_t *args = (prov_connect_args_t *)param;
    int rc = claw_wifi_mgr_connect_sta(args->ssid, args->password);
    if (rc == RTK_SUCCESS) {
        claw_config_set_wifi(args->ssid, args->password, args->security_type);
        RTK_LOGI(TAG, "prov_connect: connected, config saved\n");
    } else {
        RTK_LOGE(TAG, "prov_connect: connect failed\n");
    }
    rtos_mem_free(args);
    rtos_task_delete(NULL);
}

/* Helper: send {"ok":false,"error":"<msg>"} and return from caller */
static void send_json_err(claw_http_send_fn_t send_fn, int sock,
                          int code, const char *msg)
{
    char err[96];
    DiagSnPrintf(err, sizeof(err), "{\"ok\":false,\"error\":\"%s\"}", msg);
    send_fn(sock, code, "application/json", err, strlen(err));
}

#define LUA_SKILLS_DIR   "vfs:/skills"

/* ---- File management helpers ---- */

/* Binary-safe substring search (memmem equivalent).
 * Multipart bodies carry raw file bytes that routinely contain NUL (a JPEG's
 * 5th byte is often 0x00), so strstr() would stop scanning at the first NUL
 * and never locate the closing boundary. Search by explicit length instead. */
static const char *mem_find(const char *hay, size_t hlen,
                            const char *needle, size_t nlen)
{
    if (nlen == 0) return hay;
    if (hlen < nlen) return NULL;
    for (size_t i = 0; i + nlen <= hlen; i++) {
        if (hay[i] == needle[0] && memcmp(hay + i, needle, nlen) == 0)
            return hay + i;
    }
    return NULL;
}

static void url_decode(const char *src, char *dst, size_t dst_size)
{
    size_t i = 0, j = 0;
    while (src[i] && j + 1 < dst_size) {
        if (src[i] == '%' && src[i+1] && src[i+2]) {
            char hex[3] = {src[i+1], src[i+2], '\0'};
            dst[j++] = (char)strtol(hex, NULL, 16);
            i += 3;
        } else if (src[i] == '+') {
            dst[j++] = ' ';
            i++;
        } else {
            dst[j++] = src[i++];
        }
    }
    dst[j] = '\0';
}

static int query_get(const char *query, const char *key, char *out, size_t out_size)
{
    size_t klen = strlen(key);
    const char *p = query;
    while (p && *p) {
        if (strncmp(p, key, klen) == 0 && p[klen] == '=') {
            const char *v = p + klen + 1;
            const char *end = strchr(v, '&');
            size_t vlen = end ? (size_t)(end - v) : strlen(v);
            if (vlen >= out_size) vlen = out_size - 1;
            _memcpy(out, v, vlen);
            out[vlen] = '\0';
            return 1;
        }
        p = strchr(p, '&');
        if (p) p++;
    }
    return 0;
}

static int files_path_safe(const char *path)
{
    return path && path[0] != '\0' && !strstr(path, "..");
}

/* Accepted region prefixes and read-only flag.
 * JSON "prefix" field omits the trailing ':' (e.g. "vfs:" → "vfs");
 * JS reconstructs the full scheme with fpJoin(region, path) → "vfs:/path".
 * Display labels are handled client-side via i18n (T('region_vfs') etc.). */
typedef struct { const char *prefix; int ro; } region_entry_t;
static const region_entry_t s_regions[] = {
    { "vfs:",   0 },
    { "rolfs:", 1 },
};
#define FILES_REGION_COUNT ((int)(sizeof(s_regions)/sizeof(s_regions[0])))

/* Returns the region entry for path, or NULL if not recognized. */
static const region_entry_t *region_find(const char *path)
{
    for (int i = 0; i < FILES_REGION_COUNT; i++) {
        if (strncmp(path, s_regions[i].prefix, strlen(s_regions[i].prefix)) == 0)
            return &s_regions[i];
    }
    return NULL;
}

/* Returns 1 if the path's region is read-only (unknown regions are writable). */
static int path_is_ro(const char *path)
{
    const region_entry_t *r = region_find(path);
    return r ? r->ro : 0;
}

/* Convert incoming path to a full VFS path.
 * Paths already carrying a known region prefix (e.g. "rolfs:/...") are kept
 * as-is; plain paths (e.g. "/memory") default to the "vfs:" region. */
static void to_vfs_path(const char *path, char *out, size_t out_size)
{
    if (region_find(path)) {
        strlcpy(out, path, out_size);
    } else {
        DiagSnPrintf(out, out_size, "vfs:%s", path);
    }
}

/* GET /api/files/regions  →  list of available VFS regions */
static void handle_api_files_regions(const claw_http_request_t *req,
                                      claw_http_send_fn_t send_fn, int sock)
{
    (void)req;
    cJSON *arr = cJSON_CreateArray();
    if (!arr) { send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15); return; }
    for (int i = 0; i < FILES_REGION_COUNT; i++) {
        cJSON *entry = cJSON_CreateObject();
        if (!entry) continue;  /* OOM: skip this entry, keep going */
        /* Strip trailing ':' from the C prefix constant for the JSON field */
        size_t plen = strlen(s_regions[i].prefix);
        char prefix[16];
        size_t jlen = (plen > 0 && s_regions[i].prefix[plen - 1] == ':') ? plen - 1 : plen;
        memcpy(prefix, s_regions[i].prefix, jlen);
        prefix[jlen] = '\0';
        cJSON_AddStringToObject(entry, "prefix",   prefix);
        cJSON_AddBoolToObject(entry,   "readonly",  s_regions[i].ro);
        cJSON_AddItemToArray(arr, entry);
    }
    char *out = cJSON_PrintUnformatted(arr);
    cJSON_Delete(arr);
    if (out) { send_fn(sock, 200, "application/json", out, strlen(out)); free(out); }
    else      { send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15); }
}

/* Sorting helper for directory listing: dirs first, then files, each group alphabetical */
#define FILES_LIST_MAX 128
typedef struct { char name[128]; uint8_t is_dir; } files_entry_t;

/* ---- Recursive directory remove ---- */
static int rmdir_recursive(const char *vfs_path)
{
    void *dir = opendir(vfs_path);
    if (!dir) return remove(vfs_path);
    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL) {
        if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0) continue;
        char child[272];
        snprintf(child, sizeof(child), "%s/%s", vfs_path, ent->d_name);
        if (ent->d_type == DT_DIR)
            rmdir_recursive(child);
        else
            remove(child);
    }
    closedir(dir);
    return rmdir(vfs_path);
}

/* ---- Minimal uncompressed ZIP builder ---- */
#define ZIP_MAX_FILES  64
#define ZIP_MAX_BYTES  (192 * 1024)
#define ZIP_FILE_LIMIT (64 * 1024)

typedef struct {
    uint32_t crc32;
    uint32_t file_size;
    uint32_t local_offset;
    uint16_t fname_len;
    char     fname[256];
} zip_cd_t;

typedef struct {
    uint8_t *buf;
    size_t   cap;
    size_t   pos;
} zip_buf_t;

static int zb_ensure(zip_buf_t *z, size_t need)
{
    if (z->pos + need <= z->cap) return 1;
    size_t nc = z->cap + need + 8192;
    if (nc > ZIP_MAX_BYTES) return 0;
    uint8_t *nb = realloc(z->buf, nc);
    if (!nb) return 0;
    z->buf = nb; z->cap = nc;
    return 1;
}

static void zb_u16(zip_buf_t *z, uint16_t v)
{
    z->buf[z->pos++] = (uint8_t)(v & 0xFF);
    z->buf[z->pos++] = (uint8_t)(v >> 8);
}

static void zb_u32(zip_buf_t *z, uint32_t v)
{
    z->buf[z->pos++] = (uint8_t)(v & 0xFF);
    z->buf[z->pos++] = (uint8_t)((v >> 8) & 0xFF);
    z->buf[z->pos++] = (uint8_t)((v >> 16) & 0xFF);
    z->buf[z->pos++] = (uint8_t)(v >> 24);
}

static uint32_t zip_crc32(const uint8_t *data, size_t len)
{
    uint32_t crc = 0xFFFFFFFFu;
    for (size_t i = 0; i < len; i++) {
        crc ^= data[i];
        for (int j = 0; j < 8; j++) {
            uint32_t mask = (uint32_t)(-(int32_t)(crc & 1u));
            crc = (crc >> 1) ^ (0xEDB88320u & mask);
        }
    }
    return ~crc;
}

static int zip_add_file(zip_buf_t *z, zip_cd_t *cd, int *ncd,
                        const char *fname, const uint8_t *data, uint32_t dlen)
{
    if (*ncd >= ZIP_MAX_FILES) return 0;
    uint16_t nl = (uint16_t)strlen(fname);
    if (!zb_ensure(z, 30u + nl + dlen)) return 0;
    uint32_t crc = zip_crc32(data, dlen);
    uint32_t off = (uint32_t)z->pos;
    zb_u32(z, 0x04034B50u);
    zb_u16(z, 20); zb_u16(z, 0); zb_u16(z, 0);
    zb_u16(z, 0); zb_u16(z, 0);
    zb_u32(z, crc); zb_u32(z, dlen); zb_u32(z, dlen);
    zb_u16(z, nl); zb_u16(z, 0);
    memcpy(z->buf + z->pos, fname, nl); z->pos += nl;
    memcpy(z->buf + z->pos, data, dlen); z->pos += dlen;
    zip_cd_t *e = &cd[(*ncd)++];
    e->crc32 = crc; e->file_size = dlen; e->local_offset = off; e->fname_len = nl;
    strlcpy(e->fname, fname, sizeof(e->fname));
    return 1;
}

static void zip_finish(zip_buf_t *z, zip_cd_t *cd, int ncd)
{
    uint32_t cd_off = (uint32_t)z->pos;
    for (int i = 0; i < ncd; i++) {
        zip_cd_t *e = &cd[i];
        if (!zb_ensure(z, 46u + e->fname_len)) continue;
        zb_u32(z, 0x02014B50u);
        zb_u16(z, 0x0314); zb_u16(z, 20); zb_u16(z, 0); zb_u16(z, 0);
        zb_u16(z, 0); zb_u16(z, 0);
        zb_u32(z, e->crc32); zb_u32(z, e->file_size); zb_u32(z, e->file_size);
        zb_u16(z, e->fname_len); zb_u16(z, 0); zb_u16(z, 0);
        zb_u16(z, 0); zb_u16(z, 0); zb_u32(z, 0x81A40000u);
        zb_u32(z, e->local_offset);
        memcpy(z->buf + z->pos, e->fname, e->fname_len); z->pos += e->fname_len;
    }
    uint32_t cd_size = (uint32_t)z->pos - cd_off;
    if (!zb_ensure(z, 22)) return;
    zb_u32(z, 0x06054B50u);
    zb_u16(z, 0); zb_u16(z, 0);
    zb_u16(z, (uint16_t)ncd); zb_u16(z, (uint16_t)ncd);
    zb_u32(z, cd_size); zb_u32(z, cd_off);
    zb_u16(z, 0);
}

static void zip_scan_dir(zip_buf_t *z, zip_cd_t *cd, int *ncd,
                         const char *vfs_dir, const char *prefix)
{
    void *dir = opendir(vfs_dir);
    if (!dir) return;
    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL) {
        if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0) continue;
        char vchild[272], rel[256];
        snprintf(vchild, sizeof(vchild), "%s/%s", vfs_dir, ent->d_name);
        if (prefix[0])
            snprintf(rel, sizeof(rel), "%s/%s", prefix, ent->d_name);
        else
            strlcpy(rel, ent->d_name, sizeof(rel));
        if (ent->d_type == DT_DIR) {
            zip_scan_dir(z, cd, ncd, vchild, rel);
        } else {
            FILE *f = fopen(vchild, "rb");
            if (!f) continue;
            fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
            if (sz < 0) sz = 0;
            if (sz > ZIP_FILE_LIMIT) sz = ZIP_FILE_LIMIT;
            uint8_t *fbuf = malloc((size_t)sz + 1);
            if (fbuf) {
                size_t n = fread(fbuf, 1, (size_t)sz, f);
                zip_add_file(z, cd, ncd, rel, fbuf, (uint32_t)n);
                free(fbuf);
            }
            fclose(f);
        }
    }
    closedir(dir);
}

static int files_entry_cmp(const void *a, const void *b)
{
    const files_entry_t *ea = (const files_entry_t *)a;
    const files_entry_t *eb = (const files_entry_t *)b;
    if (ea->is_dir != eb->is_dir)
        return (int)eb->is_dir - (int)ea->is_dir;
    return strcmp(ea->name, eb->name);
}

/* GET /api/files?path=/xxx  →  JSON directory listing */
static void handle_api_files_get(const claw_http_request_t *req,
                                  claw_http_send_fn_t send_fn, int sock)
{
    char enc[256], path[256];
    if (!query_get(req->query, "path", enc, sizeof(enc))) {
        strcpy(path, "/");
    } else {
        url_decode(enc, path, sizeof(path));
    }
    if (!files_path_safe(path)) {
        const char *err = "{\"error\":\"invalid path\"}";
        send_fn(sock, 400, "application/json", err, strlen(err));
        return;
    }

    char vfs_path[264];
    to_vfs_path(path, vfs_path, sizeof(vfs_path));
    void *dir = opendir(vfs_path);
    if (!dir) {
        char err[192];
        DiagSnPrintf(err, sizeof(err), "{\"error\":\"cannot open directory\",\"path\":\"%s\"}", path);
        send_fn(sock, 404, "application/json", err, strlen(err));
        return;
    }

    /* Collect entries into a buffer, then sort */
    files_entry_t *buf = malloc(FILES_LIST_MAX * sizeof(files_entry_t));
    int count = 0;
    if (buf) {
        struct dirent *ent;
        while ((ent = readdir(dir)) != NULL) {
            if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0) continue;
            if (count >= FILES_LIST_MAX) break;
            strlcpy(buf[count].name, ent->d_name, sizeof(buf[0].name));
            buf[count].is_dir = (ent->d_type == DT_DIR) ? 1 : 0;
            count++;
        }
        qsort(buf, count, sizeof(files_entry_t), files_entry_cmp);
    }
    closedir(dir);

    cJSON *resp = cJSON_CreateObject();
    cJSON_AddStringToObject(resp, "path", path);
    cJSON_AddBoolToObject(resp, "readonly", path_is_ro(vfs_path));
    cJSON *entries = cJSON_CreateArray();
    cJSON_AddItemToObject(resp, "entries", entries);

    size_t plen = strlen(path);
    if (buf && resp && entries) {
        for (int i = 0; i < count; i++) {
            char fp[256];
            if (plen > 0 && path[plen - 1] == '/') {
                DiagSnPrintf(fp, sizeof(fp), "%s%s", path, buf[i].name);
            } else {
                DiagSnPrintf(fp, sizeof(fp), "%s/%s", path, buf[i].name);
            }
            char vfs_fp[272];
            to_vfs_path(fp, vfs_fp, sizeof(vfs_fp));
            struct stat st;
            int has_stat = (stat(vfs_fp, &st) == 0);
            cJSON *e = cJSON_CreateObject();
            cJSON_AddStringToObject(e, "name", buf[i].name);
            cJSON_AddStringToObject(e, "path", fp);
            cJSON_AddStringToObject(e, "type", buf[i].is_dir ? "dir" : "file");
            cJSON_AddNumberToObject(e, "size", (!buf[i].is_dir && has_stat) ? (long)st.st_size : -1);
            cJSON_AddNumberToObject(e, "mtime", has_stat ? (long)st.st_mtime : 0);
            cJSON_AddItemToArray(entries, e);
        }
    }
    free(buf);

    char *out = cJSON_PrintUnformatted(resp);
    cJSON_Delete(resp);
    if (out) {
        send_fn(sock, 200, "application/json", out, strlen(out));
        free(out);
    } else {
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
    }
}

/* DELETE /api/files?path=/xxx  →  delete file */
static void handle_api_files_delete(const claw_http_request_t *req,
                                     claw_http_send_fn_t send_fn, int sock)
{
    char enc[256], path[256];
    if (!query_get(req->query, "path", enc, sizeof(enc))) {
        send_fn(sock, 400, "application/json", "{\"error\":\"path required\"}", 25);
        return;
    }
    url_decode(enc, path, sizeof(path));
    if (!files_path_safe(path)) {
        send_fn(sock, 400, "application/json", "{\"error\":\"invalid path\"}", 24);
        return;
    }
    char vfs_path[264];
    to_vfs_path(path, vfs_path, sizeof(vfs_path));
    if (path_is_ro(vfs_path)) {
        send_fn(sock, 403, "application/json", "{\"ok\":false,\"error\":\"read-only filesystem\"}", 43);
        return;
    }
    struct stat st;
    if (stat(vfs_path, &st) != 0) {
        char err[192];
        DiagSnPrintf(err, sizeof(err), "{\"ok\":false,\"error\":\"not found\",\"path\":\"%s\"}", path);
        send_fn(sock, 404, "application/json", err, strlen(err));
        return;
    }
    int is_dir = ((st.st_mode & S_IFMT) == S_IFDIR);
    int ret = is_dir ? rmdir_recursive(vfs_path) : remove(vfs_path);
    if (ret != 0) {
        char err[192];
        DiagSnPrintf(err, sizeof(err), "{\"ok\":false,\"error\":\"delete failed\",\"path\":\"%s\"}", path);
        send_fn(sock, 500, "application/json", err, strlen(err));
        return;
    }
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* GET /api/files/download?path=/xxx  →  file: raw bytes; directory: uncompressed ZIP */
static void handle_api_files_download(const claw_http_request_t *req,
                                       claw_http_send_fn_t send_fn, int sock)
{
    char enc[256], path[256];
    if (!query_get(req->query, "path", enc, sizeof(enc))) {
        send_fn(sock, 400, "text/plain", "path required", 13);
        return;
    }
    url_decode(enc, path, sizeof(path));
    if (!files_path_safe(path)) {
        send_fn(sock, 400, "text/plain", "invalid path", 12);
        return;
    }

    char vfs_path[264];
    to_vfs_path(path, vfs_path, sizeof(vfs_path));

    struct stat st;
    if (stat(vfs_path, &st) != 0) {
        send_fn(sock, 404, "text/plain", "not found", 9);
        return;
    }

    if ((st.st_mode & S_IFMT) == S_IFDIR) {
        zip_cd_t *cd = malloc(ZIP_MAX_FILES * sizeof(zip_cd_t));
        if (!cd) { send_fn(sock, 500, "text/plain", "oom", 3); return; }
        int ncd = 0;
        zip_buf_t z = {0};
        z.buf = malloc(16384);
        if (!z.buf) { free(cd); send_fn(sock, 500, "text/plain", "oom", 3); return; }
        z.cap = 16384;
        zip_scan_dir(&z, cd, &ncd, vfs_path, "");
        zip_finish(&z, cd, ncd);
        free(cd);
        send_fn(sock, 200, "application/zip", (const char *)z.buf, z.pos);
        free(z.buf);
    } else {
        FILE *f = fopen(vfs_path, "rb");
        if (!f) { send_fn(sock, 404, "text/plain", "not found", 9); return; }
        long sz = st.st_size;
        if (sz < 0) sz = 0;
        /* Same cap as the read_file tool / content endpoint so a file the WebUI
         * can display is also downloadable in full. */
        if (sz > CAP_FILES_MAX_READ_SIZE) sz = CAP_FILES_MAX_READ_SIZE;
        char *buf = malloc((size_t)sz + 1);
        if (!buf) { fclose(f); send_fn(sock, 500, "text/plain", "oom", 3); return; }
        size_t n = fread(buf, 1, (size_t)sz, f);
        fclose(f);
        send_fn(sock, 200, "application/octet-stream", buf, n);
        free(buf);
    }
}

/* GET /api/files/content?path=/xxx  →  file content as text (max CAP_FILES_MAX_READ_SIZE) */
static void handle_api_files_content_get(const claw_http_request_t *req,
                                          claw_http_send_fn_t send_fn, int sock)
{
    char enc[256], path[256];
    if (!query_get(req->query, "path", enc, sizeof(enc))) {
        send_fn(sock, 400, "application/json", "{\"error\":\"path required\"}", 25);
        return;
    }
    url_decode(enc, path, sizeof(path));
    if (!files_path_safe(path)) {
        send_fn(sock, 400, "application/json", "{\"error\":\"invalid path\"}", 24);
        return;
    }

    char vfs_path[264];
    to_vfs_path(path, vfs_path, sizeof(vfs_path));

    struct stat st;
    if (stat(vfs_path, &st) != 0 || !S_ISREG(st.st_mode)) {
        send_fn(sock, 404, "application/json", "{\"error\":\"file not found\"}", 26);
        return;
    }
    if (st.st_size > CAP_FILES_MAX_READ_SIZE) {
        send_fn(sock, 413, "application/json", "{\"error\":\"file too large\"}", 26);
        return;
    }
    FILE *f = fopen(vfs_path, "r");
    if (!f) {
        send_fn(sock, 500, "application/json", "{\"error\":\"cannot open file\"}", 28);
        return;
    }
    long sz = st.st_size;
    if (sz < 0) sz = 0;
    char *buf = malloc((size_t)sz + 1);
    if (!buf) { fclose(f); send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15); return; }
    size_t n = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    buf[n] = '\0';
    /* Detect binary content (null byte) */
    for (size_t i = 0; i < n; i++) {
        if (buf[i] == '\0') {
            free(buf);
            send_fn(sock, 415, "application/json", "{\"error\":\"binary file not supported\"}", 37);
            return;
        }
    }
    send_fn(sock, 200, "text/plain; charset=utf-8", buf, n);
    free(buf);
}

/* PUT /api/files/content?path=/xxx  body=text → save file content */
static void handle_api_files_content_put(const claw_http_request_t *req,
                                          claw_http_send_fn_t send_fn, int sock)
{
    char enc[256], path[256];
    if (!query_get(req->query, "path", enc, sizeof(enc))) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"path required\"}", 36);
        return;
    }
    url_decode(enc, path, sizeof(path));
    if (!files_path_safe(path)) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"invalid path\"}", 35);
        return;
    }

    char vfs_path[264];
    to_vfs_path(path, vfs_path, sizeof(vfs_path));
    if (path_is_ro(vfs_path)) {
        send_fn(sock, 403, "application/json", "{\"ok\":false,\"error\":\"read-only filesystem\"}", 43);
        return;
    }

    /* Check parent directory exists (same logic as upload handler) */
    char dir_path[256];
    strlcpy(dir_path, path, sizeof(dir_path));
    char *slash = strrchr(dir_path, '/');
    if (slash && slash != dir_path) {
        *slash = '\0';
        char vfs_dir[264];
        to_vfs_path(dir_path, vfs_dir, sizeof(vfs_dir));
        struct stat dir_st;
        if (stat(vfs_dir, &dir_st) != 0 || (dir_st.st_mode & S_IFMT) != S_IFDIR) {
            char err[192];
            DiagSnPrintf(err, sizeof(err),
                         "{\"ok\":false,\"error\":\"directory not found\",\"path\":\"%s\"}", dir_path);
            send_fn(sock, 404, "application/json", err, strlen(err));
            return;
        }
    }

    FILE *f = fopen(vfs_path, "w");
    if (!f) {
        send_fn(sock, 500, "application/json", "{\"ok\":false,\"error\":\"cannot write file\"}", 40);
        return;
    }
    if (req->body && req->body_len > 0) {
        size_t written = fwrite(req->body, 1, req->body_len, f);
        fclose(f);
        if (written != req->body_len) {
            send_fn(sock, 500, "application/json",
                    "{\"ok\":false,\"error\":\"write incomplete\"}", 39);
            return;
        }
    } else {
        fclose(f);
    }
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* POST /api/files/upload  →  multipart/form-data upload (fields: file, path) */
static void handle_api_files_upload(const claw_http_request_t *req,
                                     claw_http_send_fn_t send_fn, int sock)
{
    const char *body = req->body;
    if (!body || req->body_len < 10 || body[0] != '-' || body[1] != '-') {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"not multipart\"}", 36);
        return;
    }

    /* Extract boundary from first line (body starts with "--BOUNDARY\r\n") */
    const char *first_eol = strstr(body, "\r\n");
    if (!first_eol) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"bad boundary\"}", 35);
        return;
    }
    char bdry[130]; /* "--BOUNDARY" including leading "--" */
    size_t bdlen = (size_t)(first_eol - body);
    if (bdlen == 0 || bdlen >= sizeof(bdry)) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"bad boundary\"}", 35);
        return;
    }
    _memcpy(bdry, body, bdlen);
    bdry[bdlen] = '\0';

    char upload_filename[128] = "";
    const char *file_data     = NULL;
    size_t      file_data_len = 0;
    char upload_dir[256]      = "/";

    /* Scan parts; each part ends at "\r\n--BOUNDARY" */
    const char *p = first_eol + 2;
    while (p && *p) {
        const char *hdr_end = strstr(p, "\r\n\r\n");
        if (!hdr_end) break;
        const char *data = hdr_end + 4;

        /* Parse field name and optional filename from Content-Disposition */
        char field_name[64] = "";
        char fn[128]        = "";
        const char *cd = strstr(p, "Content-Disposition:");
        if (cd && cd < hdr_end) {
            const char *ns = strstr(cd, "name=\"");
            if (ns && ns < hdr_end) {
                ns += 6;
                const char *ne = strchr(ns, '"');
                if (ne && ne < hdr_end) {
                    size_t nl = (size_t)(ne - ns);
                    if (nl >= sizeof(field_name)) nl = sizeof(field_name) - 1;
                    _memcpy(field_name, ns, nl);
                    field_name[nl] = '\0';
                }
            }
            const char *fs = strstr(cd, "filename=\"");
            if (fs && fs < hdr_end) {
                fs += 10;
                const char *fe = strchr(fs, '"');
                if (fe && fe < hdr_end) {
                    size_t fl = (size_t)(fe - fs);
                    if (fl >= sizeof(fn)) fl = sizeof(fn) - 1;
                    _memcpy(fn, fs, fl);
                    fn[fl] = '\0';
                }
            }
        }

        /* Find end of this part's data (next boundary). Binary-safe: the file
         * part holds raw bytes with embedded NULs, so search by length. */
        size_t data_avail = (size_t)((body + req->body_len) - data);
        const char *next_bdry = mem_find(data, data_avail, bdry, bdlen);
        if (!next_bdry) break;
        size_t dlen = (size_t)(next_bdry - data);
        /* Strip the \r\n that precedes the boundary delimiter */
        if (dlen >= 2) dlen -= 2;

        if (strcmp(field_name, "file") == 0) {
            file_data     = data;
            file_data_len = dlen;
            if (fn[0]) strlcpy(upload_filename, fn, sizeof(upload_filename));
        } else if (strcmp(field_name, "path") == 0 && dlen > 0 && dlen < sizeof(upload_dir)) {
            _memcpy(upload_dir, data, dlen);
            upload_dir[dlen] = '\0';
            /* Strip trailing \r\n */
            size_t l = strlen(upload_dir);
            while (l > 0 && (upload_dir[l-1] == '\r' || upload_dir[l-1] == '\n'))
                upload_dir[--l] = '\0';
            if (l == 0) strcpy(upload_dir, "/");
        }

        /* Advance to next part: skip past boundary + \r\n */
        p = next_bdry + bdlen;
        if (p[0] == '-' && p[1] == '-') break; /* final boundary */
        if (p[0] == '\r' && p[1] == '\n') p += 2;
        else break;
    }

    if (!file_data || upload_filename[0] == '\0') {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"no file\"}", 30);
        return;
    }
    if (!files_path_safe(upload_dir) || strstr(upload_filename, "/") || strstr(upload_filename, "..")) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"invalid path\"}", 35);
        return;
    }

    char dest[256];
    size_t dlen_dir = strlen(upload_dir);
    if (dlen_dir > 0 && upload_dir[dlen_dir - 1] == '/') {
        DiagSnPrintf(dest, sizeof(dest), "%s%s", upload_dir, upload_filename);
    } else {
        DiagSnPrintf(dest, sizeof(dest), "%s/%s", upload_dir, upload_filename);
    }

    char vfs_dest[264];
    to_vfs_path(dest, vfs_dest, sizeof(vfs_dest));
    if (path_is_ro(vfs_dest)) {
        send_fn(sock, 403, "application/json", "{\"ok\":false,\"error\":\"read-only filesystem\"}", 43);
        return;
    }
    char vfs_dir[264];
    to_vfs_path(upload_dir, vfs_dir, sizeof(vfs_dir));
    struct stat dir_st;
    if (stat(vfs_dir, &dir_st) != 0 || (dir_st.st_mode & S_IFMT) != S_IFDIR) {
        char err[192];
        snprintf(err, sizeof(err), "{\"ok\":false,\"error\":\"directory not found\",\"path\":\"%s\"}", upload_dir);
        send_fn(sock, 404, "application/json", err, strlen(err));
        return;
    }
    FILE *f = fopen(vfs_dest, "wb");
    if (!f) {
        char err[192];
        DiagSnPrintf(err, sizeof(err), "{\"ok\":false,\"error\":\"cannot write\",\"path\":\"%s\"}", dest);
        send_fn(sock, 500, "application/json", err, strlen(err));
        return;
    }
    size_t wr1 = fwrite(file_data, 1, file_data_len, f);
    fclose(f);
    if (wr1 != file_data_len) {
        send_fn(sock, 500, "application/json",
                "{\"ok\":false,\"error\":\"write incomplete\"}", 39);
        return;
    }
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* POST /api/files/mkdir?path=/xxx  →  create directory */
static void handle_api_files_mkdir(const claw_http_request_t *req,
                                    claw_http_send_fn_t send_fn, int sock)
{
    char enc[256], path[256];
    if (!query_get(req->query, "path", enc, sizeof(enc))) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"path required\"}", 36);
        return;
    }
    url_decode(enc, path, sizeof(path));
    if (!files_path_safe(path)) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"invalid path\"}", 35);
        return;
    }
    char vfs_path[264];
    to_vfs_path(path, vfs_path, sizeof(vfs_path));
    if (path_is_ro(vfs_path)) {
        send_fn(sock, 403, "application/json", "{\"ok\":false,\"error\":\"read-only filesystem\"}", 43);
        return;
    }
    if (mkdir(vfs_path, 0777) != 0) {
        char err[192];
        snprintf(err, sizeof(err), "{\"ok\":false,\"error\":\"mkdir failed\",\"path\":\"%s\"}", path);
        send_fn(sock, 500, "application/json", err, strlen(err));
        return;
    }
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* ---- Handlers ---- */

static void handle_favicon(const claw_http_request_t *req,
                            claw_http_send_fn_t send_fn, int sock)
{
    (void)req;
    send_fn(sock, 200, "image/x-icon",
            (const char *)_res_favicon_ico_start,
            (size_t)(_res_favicon_ico_end - _res_favicon_ico_start));
}

static void handle_index(const claw_http_request_t *req,
                          claw_http_send_fn_t send_fn, int sock)
{
    char hdr[320];
    int n;
    (void)req;
    (void)send_fn;
    n = snprintf(hdr, sizeof(hdr),
                 "HTTP/1.1 200 OK\r\n"
                 "Content-Type: text/html; charset=utf-8\r\n"
                 "Content-Encoding: gzip\r\n"
                 "Content-Length: %u\r\n"
                 "Access-Control-Allow-Origin: *\r\n"
                 "Connection: close\r\n"
                 "\r\n",
                 (unsigned)_res_dashboard_html_size);
    lwip_send(sock, hdr, n, 0);
    lwip_send(sock, (const char *)_res_dashboard_html_start,
              _res_dashboard_html_size, 0);
}

static void handle_status(const claw_http_request_t *req,
                           claw_http_send_fn_t send_fn, int sock)
{
    (void)req;
    const claw_config_t *cfg   = claw_config_get();
    claw_wifi_state_t    state = claw_wifi_mgr_get_state();
    bool                 connected = (state == CLAW_WIFI_STATE_CONNECTED);
    const char          *ip    = claw_wifi_mgr_get_sta_ip();
    bool                 softap_up = claw_wifi_mgr_is_softap_running();
    uint32_t             free_heap = rtos_mem_get_free_heap_size();
    uint32_t             min_heap  = rtos_mem_get_minimum_ever_free_heap_size();

    const char *connect_err = claw_wifi_mgr_get_connect_error();

    /* Build the status response with cJSON so all string fields are
     * properly JSON-escaped (prevents injection via crafted SSID etc.). */
    cJSON *root = cJSON_CreateObject();
    if (!root) {
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        return;
    }

    cJSON *wifi_obj = cJSON_CreateObject();
    cJSON_AddBoolToObject(wifi_obj,   "connected",     connected);
    cJSON_AddBoolToObject(wifi_obj,   "configured",    cfg->wifi.configured);
    cJSON_AddStringToObject(wifi_obj, "ssid",          cfg->wifi.ssid);
    cJSON_AddStringToObject(wifi_obj, "security_type", cfg->wifi.security_type);
    cJSON_AddStringToObject(wifi_obj, "ip",            ip ? ip : "");
    cJSON_AddStringToObject(wifi_obj, "connect_error", connect_err ? connect_err : "");
    cJSON_AddItemToObject(root, "wifi", wifi_obj);

    cJSON *softap_obj = cJSON_CreateObject();
    cJSON_AddBoolToObject(softap_obj,   "running", softap_up);
    cJSON_AddStringToObject(softap_obj, "ssid",    cfg->softap.ssid);
    cJSON_AddStringToObject(softap_obj, "ip",      "192.168.1.1");
    cJSON_AddItemToObject(root, "softap", softap_obj);

    cJSON_AddStringToObject(root, "mode",      softap_up && !connected ? "provisioning" : "normal");
    cJSON_AddStringToObject(root, "version",   "1.0");

    cJSON *heap_obj = cJSON_CreateObject();
    cJSON_AddNumberToObject(heap_obj, "free_bytes",     (double)free_heap);
    cJSON_AddNumberToObject(heap_obj, "min_ever_bytes", (double)min_heap);
    cJSON_AddItemToObject(root, "heap", heap_obj);

    char *json_str = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (!json_str) {
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        return;
    }
    send_fn(sock, 200, "application/json", json_str, strlen(json_str));
    free(json_str);
}


static void handle_api_config(const claw_http_request_t *req,
                               claw_http_send_fn_t send_fn, int sock)
{
    (void)req;
    const claw_config_t *cfg = claw_config_get();

    cJSON *root = cJSON_CreateObject();
    if (!root) {
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        return;
    }

    cJSON *wifi = cJSON_CreateObject();
    cJSON_AddStringToObject(wifi, "ssid",          cfg->wifi.ssid);
    cJSON_AddStringToObject(wifi, "password",      cfg->wifi.password);
    cJSON_AddStringToObject(wifi, "security_type", cfg->wifi.security_type);
    cJSON_AddBoolToObject(  wifi, "configured",    cfg->wifi.configured);
    cJSON_AddItemToObject(root, "wifi", wifi);

    cJSON *llm = cJSON_CreateObject();
    cJSON_AddStringToObject(llm, "api_url",        cfg->llm.api_url);
    cJSON_AddStringToObject(llm, "api_key",        cfg->llm.api_key);
    cJSON_AddStringToObject(llm, "model",          cfg->llm.model);
    cJSON_AddNumberToObject(llm, "max_tokens",     cfg->llm.max_tokens);
    cJSON_AddNumberToObject(llm, "max_iterations", cfg->llm.max_iterations);
    cJSON_AddNumberToObject(llm, "backend",        cfg->llm.backend);
    cJSON_AddBoolToObject(  llm, "thinking",       cfg->llm.thinking_enabled);
    cJSON_AddBoolToObject(  llm, "stream",         cfg->llm.stream_enabled);
    cJSON_AddNumberToObject(llm, "compact_tokens", cfg->llm.compact_tokens);
    cJSON_AddNumberToObject(llm, "window_tokens",  cfg->llm.window_tokens);
    cJSON_AddItemToObject(root, "llm", llm);

    cJSON *tg = cJSON_CreateObject();
    cJSON_AddStringToObject(tg, "bot_token", cfg->telegram.bot_token);
    cJSON_AddItemToObject(root, "telegram", tg);

    cJSON *fs = cJSON_CreateObject();
    cJSON_AddStringToObject(fs, "app_id",     cfg->feishu.app_id);
    cJSON_AddStringToObject(fs, "app_secret", cfg->feishu.app_secret);
    cJSON_AddItemToObject(root, "feishu", fs);

    cJSON *qq = cJSON_CreateObject();
    cJSON_AddStringToObject(qq, "app_id",     cfg->qq.app_id);
    cJSON_AddStringToObject(qq, "app_secret", cfg->qq.app_secret);
    cJSON_AddItemToObject(root, "qq", qq);

    cJSON *wx = cJSON_CreateObject();
    cJSON_AddStringToObject(wx, "base_url", cfg->wechat.base_url);
    cJSON_AddStringToObject(wx, "app_id",   cfg->wechat.app_id);
    cJSON_AddItemToObject(root, "wechat", wx);

    cJSON *ws = cJSON_CreateObject();
    cJSON_AddStringToObject(ws, "api_key",     cfg->web_search.api_key);
    cJSON_AddNumberToObject(ws, "max_results", cfg->web_search.max_results);
    cJSON_AddItemToObject(root, "search", ws);

    cJSON *hr = cJSON_CreateObject();
    cJSON_AddStringToObject(hr, "allowlist", cfg->http_request.allowlist);
    cJSON_AddItemToObject(root, "http_request", hr);

    cJSON *cap_vis = cJSON_CreateObject();
    cJSON *hidden_arr = cJSON_CreateArray();
    for (uint8_t i = 0; i < cfg->cap_visibility.hidden_count; i++) {
        cJSON_AddItemToArray(hidden_arr, cJSON_CreateString(cfg->cap_visibility.hidden[i]));
    }
    cJSON_AddItemToObject(cap_vis, "hidden", hidden_arr);
    cJSON_AddItemToObject(root, "cap_visibility", cap_vis);

    char *json = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);

    if (!json) {
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        return;
    }

    send_fn(sock, 200, "application/json", json, strlen(json));
    free(json);
}

static void handle_setup_post(const claw_http_request_t *req,
                               claw_http_send_fn_t send_fn, int sock)
{
    const char *resp_ok = "{\"ok\":true}";

    if (!req->body || req->body_len == 0) {
        send_json_err(send_fn, sock, 400, "empty body");
        return;
    }

    cJSON *root = cJSON_ParseWithLength(req->body, req->body_len);
    if (!root) {
        send_json_err(send_fn, sock, 400, "invalid JSON");
        return;
    }

    cJSON *sec_j = cJSON_GetObjectItemCaseSensitive(root, "section");
    if (!sec_j || !cJSON_IsString(sec_j)) {
        cJSON_Delete(root);
        send_json_err(send_fn, sock, 400, "section required");
        return;
    }

    const char *section = sec_j->valuestring;
    int rc = RTK_SUCCESS;

    if (strcmp(section, "wifi") == 0) {
        cJSON *ssid_j = cJSON_GetObjectItemCaseSensitive(root, "ssid");
        cJSON *pw_j   = cJSON_GetObjectItemCaseSensitive(root, "password");
        cJSON *sec2_j = cJSON_GetObjectItemCaseSensitive(root, "security_type");

        const char *ssid = (ssid_j && cJSON_IsString(ssid_j)) ? ssid_j->valuestring : NULL;
        const char *pw   = (pw_j   && cJSON_IsString(pw_j))   ? pw_j->valuestring   : "";
        const char *sec2 = (sec2_j && cJSON_IsString(sec2_j)) ? sec2_j->valuestring : "WPA2";

        if (!ssid || ssid[0] == '\0') {
            cJSON_Delete(root);
            send_json_err(send_fn, sock, 400, "ssid required");
            return;
        }
        rc = claw_config_set_wifi(ssid, pw, sec2);

    } else if (strcmp(section, "llm") == 0) {
        cJSON *url_j  = cJSON_GetObjectItemCaseSensitive(root, "api_url");
        cJSON *key_j  = cJSON_GetObjectItemCaseSensitive(root, "api_key");
        cJSON *mod_j  = cJSON_GetObjectItemCaseSensitive(root, "model");
        cJSON *tok_j  = cJSON_GetObjectItemCaseSensitive(root, "max_tokens");
        cJSON *iter_j = cJSON_GetObjectItemCaseSensitive(root, "max_iterations");
        cJSON *bk_j   = cJSON_GetObjectItemCaseSensitive(root, "backend");
        cJSON *think_j = cJSON_GetObjectItemCaseSensitive(root, "thinking");
        cJSON *strm_j  = cJSON_GetObjectItemCaseSensitive(root, "stream");
        cJSON *cmpt_j  = cJSON_GetObjectItemCaseSensitive(root, "compact_tokens");
        cJSON *win_j   = cJSON_GetObjectItemCaseSensitive(root, "window_tokens");

        const char *url  = (url_j  && cJSON_IsString(url_j))  ? url_j->valuestring  : "";
        const char *key  = (key_j  && cJSON_IsString(key_j))  ? key_j->valuestring  : "";
        const char *mod  = (mod_j  && cJSON_IsString(mod_j))  ? mod_j->valuestring  : "glm-5.1";
        uint32_t tok  = (tok_j  && cJSON_IsNumber(tok_j))  ? (uint32_t)tok_j->valueint  : 1024;
        uint8_t  iter = (iter_j && cJSON_IsNumber(iter_j)) ? (uint8_t)iter_j->valueint  : 5;
        int      bk   = (bk_j   && cJSON_IsNumber(bk_j))  ? (int)bk_j->valueint        : -1;
        /* absent → keep current (-1); present bool → on/off */
        int think = cJSON_IsBool(think_j) ? (cJSON_IsTrue(think_j) ? 1 : 0) : -1;
        int strm  = cJSON_IsBool(strm_j)  ? (cJSON_IsTrue(strm_j)  ? 1 : 0) : -1;
        /* absent / 0 → keep current */
        uint32_t cmpt = (cmpt_j && cJSON_IsNumber(cmpt_j)) ? (uint32_t)cmpt_j->valuedouble : 0;
        uint32_t win  = (win_j  && cJSON_IsNumber(win_j))  ? (uint32_t)win_j->valuedouble  : 0;

        rc = claw_config_set_llm(key, mod, url, tok, iter, bk, think, strm, cmpt, win);

#ifdef CONFIG_CLAW_CAP_IM_TELEGRAM
    } else if (strcmp(section, "telegram") == 0) {
        cJSON *tok_j = cJSON_GetObjectItemCaseSensitive(root, "bot_token");
        const char *token = (tok_j && cJSON_IsString(tok_j)) ? tok_j->valuestring : "";
        rc = claw_config_set_telegram(token);
#endif

#ifdef CONFIG_CLAW_CAP_IM_FEISHU
    } else if (strcmp(section, "feishu") == 0) {
        cJSON *id_j  = cJSON_GetObjectItemCaseSensitive(root, "app_id");
        cJSON *sec2_j = cJSON_GetObjectItemCaseSensitive(root, "app_secret");
        const char *app_id  = (id_j   && cJSON_IsString(id_j))   ? id_j->valuestring   : "";
        const char *app_sec = (sec2_j && cJSON_IsString(sec2_j)) ? sec2_j->valuestring : "";
        rc = claw_config_set_feishu(app_id, app_sec);
#endif

#ifdef CONFIG_CLAW_CAP_IM_QQ
    } else if (strcmp(section, "qq") == 0) {
        cJSON *id_j  = cJSON_GetObjectItemCaseSensitive(root, "app_id");
        cJSON *sec_j = cJSON_GetObjectItemCaseSensitive(root, "app_secret");
        const char *app_id  = (id_j  && cJSON_IsString(id_j))  ? id_j->valuestring  : NULL;
        const char *app_sec = (sec_j && cJSON_IsString(sec_j)) ? sec_j->valuestring : NULL;
        rc = claw_config_set_qq(app_id, app_sec, -1); /* msg_type intentionally not exposed; fixed at 0 (text) to simplify config */
#endif

#ifdef CONFIG_CLAW_CAP_IM_WECHAT
    } else if (strcmp(section, "wechat") == 0) {
        cJSON *url_j = cJSON_GetObjectItemCaseSensitive(root, "base_url");
        cJSON *aid_j = cJSON_GetObjectItemCaseSensitive(root, "app_id");
        cJSON *tok_j = cJSON_GetObjectItemCaseSensitive(root, "bot_token");
        const char *base_url  = (url_j && cJSON_IsString(url_j)) ? url_j->valuestring : "";
        const char *app_id    = (aid_j && cJSON_IsString(aid_j)) ? aid_j->valuestring : "";
        const char *bot_token = (tok_j && cJSON_IsString(tok_j)) ? tok_j->valuestring : NULL;
        rc = claw_config_set_wechat(base_url, app_id);
        if (rc == RTK_SUCCESS && bot_token)
            cap_im_wechat_store_token(bot_token);
#endif

#if defined(CONFIG_CLAW_CAP_IM_TELEGRAM) || defined(CONFIG_CLAW_CAP_IM_FEISHU) || defined(CONFIG_CLAW_CAP_IM_WECHAT) || defined(CONFIG_CLAW_CAP_IM_QQ)
    } else if (strcmp(section, "imbot") == 0) {
        /* Unified IM bot save: all four platforms in one request */
        const char *wx_url = "";
#ifdef CONFIG_CLAW_CAP_IM_WECHAT
        const char *wx_tok = NULL;
#endif
        const char *fs_id  = "";
        const char *fs_sec = "";
        const char *tg_tok = "";
        const char *qq_id  = "";
        const char *qq_sec = "";

#ifdef CONFIG_CLAW_CAP_IM_WECHAT
        {
            cJSON *wx_j = cJSON_GetObjectItemCaseSensitive(root, "wechat");
            if (wx_j && cJSON_IsObject(wx_j)) {
                cJSON *u = cJSON_GetObjectItemCaseSensitive(wx_j, "base_url");
                cJSON *t = cJSON_GetObjectItemCaseSensitive(wx_j, "bot_token");
                if (u && cJSON_IsString(u)) wx_url = u->valuestring;
                if (t && cJSON_IsString(t)) wx_tok = t->valuestring;
            }
        }
#endif
#ifdef CONFIG_CLAW_CAP_IM_FEISHU
        {
            cJSON *fs_j = cJSON_GetObjectItemCaseSensitive(root, "feishu");
            if (fs_j && cJSON_IsObject(fs_j)) {
                cJSON *i = cJSON_GetObjectItemCaseSensitive(fs_j, "app_id");
                cJSON *p = cJSON_GetObjectItemCaseSensitive(fs_j, "app_secret");
                if (i && cJSON_IsString(i)) fs_id  = i->valuestring;
                if (p && cJSON_IsString(p)) fs_sec = p->valuestring;
            }
        }
#endif
#ifdef CONFIG_CLAW_CAP_IM_TELEGRAM
        {
            cJSON *tg_j = cJSON_GetObjectItemCaseSensitive(root, "telegram");
            if (tg_j && cJSON_IsObject(tg_j)) {
                cJSON *t = cJSON_GetObjectItemCaseSensitive(tg_j, "bot_token");
                if (t && cJSON_IsString(t)) tg_tok = t->valuestring;
            }
        }
#endif
#ifdef CONFIG_CLAW_CAP_IM_QQ
        {
            cJSON *qq_j = cJSON_GetObjectItemCaseSensitive(root, "qq");
            if (qq_j && cJSON_IsObject(qq_j)) {
                cJSON *i = cJSON_GetObjectItemCaseSensitive(qq_j, "app_id");
                cJSON *s = cJSON_GetObjectItemCaseSensitive(qq_j, "app_secret");
                if (i && cJSON_IsString(i)) qq_id  = i->valuestring;
                if (s && cJSON_IsString(s)) qq_sec = s->valuestring;
            }
        }
#endif
        rc = claw_config_set_imbot(wx_url, fs_id, fs_sec, tg_tok, qq_id, qq_sec);
#ifdef CONFIG_CLAW_CAP_IM_WECHAT
        if (rc == RTK_SUCCESS && wx_tok)
            cap_im_wechat_store_token(wx_tok);
#endif
#endif /* any IM enabled */

    } else if (strcmp(section, "search") == 0) {
        cJSON *key_j = cJSON_GetObjectItemCaseSensitive(root, "api_key");
        cJSON *n_j   = cJSON_GetObjectItemCaseSensitive(root, "max_results");
        const char *api_key = (key_j && cJSON_IsString(key_j)) ? key_j->valuestring : "";
        uint8_t max_res = (n_j && cJSON_IsNumber(n_j) && n_j->valueint > 0)
                          ? (uint8_t)n_j->valueint
                          : CLAW_CONFIG_DEFAULT_SEARCH_MAX_RESULTS;
        rc = claw_config_set_search(api_key, max_res);

    } else if (strcmp(section, "http_request") == 0) {
        cJSON *al_j = cJSON_GetObjectItemCaseSensitive(root, "allowlist");
        const char *allowlist = (al_j && cJSON_IsString(al_j)) ? al_j->valuestring : "";

        /* Check total allowlist length fits in config storage (strlcpy would
         * silently truncate otherwise, potentially splitting a rule mid-line). */
        if (strlen(allowlist) >= CLAW_HTTP_REQUEST_ALLOWLIST_MAX) {
            cJSON_Delete(root);
            send_json_err(send_fn, sock, 400, "allowlist too long");
            return;
        }

        /* Validate each non-empty rule:
         *   - hostname length ≤ 253 chars (DNS maximum)
         *   - allowed chars [a-zA-Z0-9.\-*:_] only
         * Heap-allocate the working copy to stay within the 128-byte stack
         * variable limit (CLAW_HTTP_REQUEST_ALLOWLIST_MAX = 512). */
        static const char RULE_ALLOWED[] =
            "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.-*:_";
        char *rule_buf = (char *)rtos_mem_malloc(CLAW_HTTP_REQUEST_ALLOWLIST_MAX);
        if (!rule_buf) {
            cJSON_Delete(root);
            send_json_err(send_fn, sock, 500, "out of memory");
            return;
        }
        strlcpy(rule_buf, allowlist, CLAW_HTTP_REQUEST_ALLOWLIST_MAX);
        char *rline = rule_buf;
        int   rule_valid = 1;
        char  bad_rule[64] = {0};
        while (rline && *rline) {
            char *rnext = strchr(rline, '\n');
            if (rnext) *rnext++ = '\0';
            /* trim */
            while (*rline == ' ' || *rline == '\r') rline++;
            char *rend = rline + strlen(rline);
            while (rend > rline && (*(rend-1) == ' ' || *(rend-1) == '\r')) rend--;
            *rend = '\0';
            if (*rline) {
                /* Reject rules whose hostname exceeds the DNS 253-char limit. */
                if ((size_t)(rend - rline) > 253) {
                    rtos_mem_free(rule_buf);
                    cJSON_Delete(root);
                    char trunc[61];
                    strlcpy(trunc, rline, sizeof(trunc));
                    char err_buf[128];
                    DiagSnPrintf(err_buf, sizeof(err_buf),
                                 "{\"ok\":false,\"error\":\"allowlist rule too long (max 253 chars): %s\"}",
                                 trunc);
                    send_fn(sock, 400, "application/json", err_buf, strlen(err_buf));
                    return;
                }
                for (const char *p = rline; *p; p++) {
                    if (!strchr(RULE_ALLOWED, *p)) {
                        strlcpy(bad_rule, rline, sizeof(bad_rule));
                        rule_valid = 0;
                        break;
                    }
                }
            }
            if (!rule_valid) break;
            rline = rnext;
        }
        rtos_mem_free(rule_buf);

        if (!rule_valid) {
            cJSON_Delete(root);
            /* Return 400 with specific bad rule */
            char err_buf[128];
            DiagSnPrintf(err_buf, sizeof(err_buf),
                         "{\"ok\":false,\"error\":\"invalid allowlist rule: %s\"}", bad_rule);
            send_fn(sock, 400, "application/json", err_buf, strlen(err_buf));
            return;
        }

        rc = claw_config_set_http_request(allowlist);

    } else {
        cJSON_Delete(root);
        send_json_err(send_fn, sock, 400, "unknown section");
        return;
    }

    cJSON_Delete(root);

    if (rc != RTK_SUCCESS) {
        send_json_err(send_fn, sock, 500, "save failed");
        return;
    }

    send_fn(sock, 200, "application/json", resp_ok, strlen(resp_ok));
}

static void handle_wifi_connect(const claw_http_request_t *req,
                                 claw_http_send_fn_t send_fn, int sock)
{
    if (!req->body || req->body_len == 0) {
        send_json_err(send_fn, sock, 400, "empty body");
        return;
    }

    cJSON *root = cJSON_ParseWithLength(req->body, req->body_len);
    if (!root) {
        send_json_err(send_fn, sock, 400, "invalid JSON");
        return;
    }

    cJSON *ssid_j = cJSON_GetObjectItemCaseSensitive(root, "ssid");
    cJSON *pw_j   = cJSON_GetObjectItemCaseSensitive(root, "password");

    const char *ssid = (ssid_j && cJSON_IsString(ssid_j)) ? ssid_j->valuestring : NULL;
    const char *pw   = (pw_j   && cJSON_IsString(pw_j))   ? pw_j->valuestring   : "";

    if (!ssid || ssid[0] == '\0') {
        cJSON_Delete(root);
        send_json_err(send_fn, sock, 400, "ssid required");
        return;
    }

    if (strlen(ssid) > RTW_ESSID_MAX_SIZE) {
        cJSON_Delete(root);
        send_json_err(send_fn, sock, 400, "ssid too long");
        return;
    }

    /* Spawn async task so we can respond before the WiFi channel switch
     * disrupts the SoftAP connection.  Frontend polls GET /status for the IP. */
    prov_connect_args_t *args = (prov_connect_args_t *)rtos_mem_malloc(sizeof(*args));
    if (!args) {
        cJSON_Delete(root);
        send_json_err(send_fn, sock, 500, "out of memory");
        return;
    }
    strlcpy(args->ssid, ssid, sizeof(args->ssid));
    strlcpy(args->password, pw ? pw : "", sizeof(args->password));
    strlcpy(args->security_type, (pw && pw[0] != '\0') ? "WPA2" : "OPEN",
            sizeof(args->security_type));
    cJSON_Delete(root);

    /* Send response BEFORE creating the task: the new task may preempt and
     * trigger a WiFi channel switch that would drop the TCP connection,
     * preventing the body from being delivered if we send after task_create. */
    const char *resp_connecting = "{\"ok\":true,\"connecting\":true}";
    send_fn(sock, 200, "application/json", resp_connecting, strlen(resp_connecting));

    if (rtos_task_create(NULL, "prov_conn", prov_connect_task,
                         args, 4096, 2) != RTK_SUCCESS) {
        RTK_LOGE(TAG, "prov_connect: task create failed, connect will not proceed\n");
        rtos_mem_free(args);
    }
}

static void handle_system_restart(const claw_http_request_t *req,
                                   claw_http_send_fn_t send_fn, int sock)
{
    (void)req;
    RTK_LOGI(TAG, "system restart requested via WebUI\n");
    const char *body = "{\"ok\":true}";
    send_fn(sock, 200, "application/json", body, strlen(body));
    rtos_time_delay_ms(500);
    sys_reset();
}

static void handle_wifi_scan(const claw_http_request_t *req,
                              claw_http_send_fn_t send_fn, int sock)
{
    (void)req;
    const char *body = "{\"networks\":[]}";
    send_fn(sock, 200, "application/json", body, strlen(body));
}

#ifdef CONFIG_CLAW_CAP_IM_WECHAT
static void handle_wechat_qrcode(const claw_http_request_t *req,
                                   claw_http_send_fn_t send_fn, int sock)
{
    char qr_url[256];
    char buf[384];
    int rc;
    (void)req;

    rc = cap_im_wechat_get_qr(qr_url, sizeof(qr_url));

    if (rc == 0) {
        DiagSnPrintf(buf, sizeof(buf), "{\"ok\":true,\"qr_url\":\"%s\"}", qr_url);
        send_fn(sock, 200, "application/json", buf, strlen(buf));
    } else if (rc == -4) {
        const char *b = "{\"ok\":false,\"error\":\"wifi_not_connected\"}";
        send_fn(sock, 503, "application/json", b, strlen(b));
    } else {
        const char *b = "{\"ok\":false,\"error\":\"qr_fetch_failed\"}";
        send_fn(sock, 500, "application/json", b, strlen(b));
    }
}

static void handle_wechat_status(const claw_http_request_t *req,
                                   claw_http_send_fn_t send_fn, int sock)
{
    char buf[384];
    (void)req;
    cap_im_wechat_get_status_json(buf, sizeof(buf));
    send_fn(sock, 200, "application/json", buf, strlen(buf));
}

static void handle_wechat_token_get(const claw_http_request_t *req,
                                     claw_http_send_fn_t send_fn, int sock)
{
    char *token = (char *)rtos_mem_malloc(256);
    char *buf   = (char *)rtos_mem_malloc(288);
    (void)req;

    if (!token || !buf) {
        rtos_mem_free(token);
        rtos_mem_free(buf);
        send_fn(sock, 500, "application/json", "{\"ok\":false}", 12);
        return;
    }

    if (cap_im_wechat_get_token(token, 256) == 0 && token[0]) {
        DiagSnPrintf(buf, 288, "{\"ok\":true,\"token\":\"%s\"}", token);
    } else {
        DiagSnPrintf(buf, 288, "{\"ok\":true,\"token\":\"\"}");
    }
    send_fn(sock, 200, "application/json", buf, strlen(buf));
    rtos_mem_free(token);
    rtos_mem_free(buf);
}
#endif /* CONFIG_CLAW_CAP_IM_WECHAT */

/* ---- Lua script management (/api/lua) ---- */

static int lua_name_safe(const char *name)
{
    if (!name || !name[0]) return 0;
    if (strstr(name, "/") || strstr(name, "..")) return 0;
    return 1;
}

/* GET /api/lua → {files:[{name,size},...]} */
static void handle_api_lua_list(const claw_http_request_t *req,
                                  claw_http_send_fn_t send_fn, int sock)
{
    (void)req;
    void *dir = opendir(LUA_SKILLS_DIR);
    if (!dir) {
        send_fn(sock, 200, "application/json", "{\"files\":[]}", 12);
        return;
    }

    cJSON *resp = cJSON_CreateObject();
    cJSON *arr  = cJSON_CreateArray();
    if (resp && arr) {
        cJSON_AddItemToObject(resp, "files", arr);
        struct dirent *ent;
        while ((ent = readdir(dir)) != NULL) {
            if (ent->d_type == DT_DIR) continue;
            size_t nlen = strlen(ent->d_name);
            if (nlen < 5 || strcmp(ent->d_name + nlen - 4, ".lua") != 0) continue;
            char fp[160];
            DiagSnPrintf(fp, sizeof(fp), "%s/%s", LUA_SKILLS_DIR, ent->d_name);
            long fsize = 0;
            struct stat st;
            if (stat(fp, &st) == 0) fsize = (long)st.st_size;
            cJSON *e = cJSON_CreateObject();
            if (e) {
                cJSON_AddStringToObject(e, "name", ent->d_name);
                cJSON_AddNumberToObject(e, "size", fsize);
                cJSON_AddItemToArray(arr, e);
            }
        }
    }
    closedir(dir);

    char *out = resp ? cJSON_PrintUnformatted(resp) : NULL;
    cJSON_Delete(resp);
    if (out) {
        send_fn(sock, 200, "application/json", out, strlen(out));
        free(out);
    } else {
        send_fn(sock, 200, "application/json", "{\"files\":[]}", 12);
    }
}

/* GET /api/lua/content?name=xxx → raw script content */
static void handle_api_lua_content_get(const claw_http_request_t *req,
                                         claw_http_send_fn_t send_fn, int sock)
{
    char enc[128], name[128];
    if (!query_get(req->query, "name", enc, sizeof(enc))) {
        send_fn(sock, 400, "text/plain", "name required", 13);
        return;
    }
    url_decode(enc, name, sizeof(name));
    if (!lua_name_safe(name)) {
        send_fn(sock, 400, "text/plain", "invalid name", 12);
        return;
    }

    char path[192];
    DiagSnPrintf(path, sizeof(path), "%s/%s", LUA_SKILLS_DIR, name);
    FILE *f = fopen(path, "r");
    if (!f) {
        send_fn(sock, 404, "text/plain", "not found", 9);
        return;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (sz < 0) sz = 0;
    if (sz > 32768) sz = 32768;
    char *buf = malloc((size_t)sz + 1);
    if (!buf) {
        fclose(f);
        send_fn(sock, 500, "text/plain", "oom", 3);
        return;
    }
    size_t rlen = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    send_fn(sock, 200, "text/plain; charset=utf-8", buf, rlen);
    free(buf);
}

/* PUT /api/lua/content?name=xxx, body=script text → {ok:true} */
static void handle_api_lua_content_put(const claw_http_request_t *req,
                                         claw_http_send_fn_t send_fn, int sock)
{
    char enc[128], name[128];
    if (!query_get(req->query, "name", enc, sizeof(enc))) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"name required\"}", 36);
        return;
    }
    url_decode(enc, name, sizeof(name));
    if (!lua_name_safe(name)) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"invalid name\"}", 35);
        return;
    }

    char path[192];
    DiagSnPrintf(path, sizeof(path), "%s/%s", LUA_SKILLS_DIR, name);
    FILE *f = fopen(path, "w");
    if (!f) {
        mkdir(LUA_SKILLS_DIR, 0777);
        f = fopen(path, "w");
    }
    if (!f) {
        send_fn(sock, 500, "application/json", "{\"ok\":false,\"error\":\"cannot write\"}", 35);
        return;
    }
    if (req->body && req->body_len > 0) {
        size_t written = fwrite(req->body, 1, req->body_len, f);
        fclose(f);
        if (written != req->body_len) {
            send_fn(sock, 500, "application/json",
                    "{\"ok\":false,\"error\":\"write incomplete\"}", 39);
            return;
        }
    } else {
        fclose(f);
    }
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* POST /api/lua/upload → multipart upload, saves to skills dir */
static void handle_api_lua_upload(const claw_http_request_t *req,
                                    claw_http_send_fn_t send_fn, int sock)
{
    const char *body = req->body;
    if (!body || req->body_len < 10 || body[0] != '-' || body[1] != '-') {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"not multipart\"}", 36);
        return;
    }
    const char *first_eol = strstr(body, "\r\n");
    if (!first_eol) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"bad boundary\"}", 35);
        return;
    }
    char bdry[130];
    size_t bdlen = (size_t)(first_eol - body);
    if (bdlen == 0 || bdlen >= sizeof(bdry)) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"bad boundary\"}", 35);
        return;
    }
    memcpy(bdry, body, bdlen);
    bdry[bdlen] = '\0';

    char upload_filename[128] = "";
    const char *file_data = NULL;
    size_t file_data_len = 0;

    const char *p = first_eol + 2;
    while (p && *p) {
        const char *hdr_end = strstr(p, "\r\n\r\n");
        if (!hdr_end) break;
        const char *data = hdr_end + 4;
        char field_name[64] = "", fn[128] = "";
        const char *cd = strstr(p, "Content-Disposition:");
        if (cd && cd < hdr_end) {
            const char *ns = strstr(cd, "name=\"");
            if (ns && ns < hdr_end) {
                ns += 6;
                const char *ne = strchr(ns, '"');
                if (ne && ne < hdr_end) {
                    size_t nl = (size_t)(ne - ns);
                    if (nl >= sizeof(field_name)) nl = sizeof(field_name) - 1;
                    memcpy(field_name, ns, nl); field_name[nl] = '\0';
                }
            }
            const char *fs = strstr(cd, "filename=\"");
            if (fs && fs < hdr_end) {
                fs += 10;
                const char *fe = strchr(fs, '"');
                if (fe && fe < hdr_end) {
                    size_t fl = (size_t)(fe - fs);
                    if (fl >= sizeof(fn)) fl = sizeof(fn) - 1;
                    memcpy(fn, fs, fl); fn[fl] = '\0';
                }
            }
        }
        size_t data_avail = (size_t)((body + req->body_len) - data);
        const char *next_bdry = mem_find(data, data_avail, bdry, bdlen);
        if (!next_bdry) break;
        size_t dlen_d = (size_t)(next_bdry - data);
        if (dlen_d >= 2) dlen_d -= 2;
        if (strcmp(field_name, "file") == 0) {
            file_data = data;
            file_data_len = dlen_d;
            if (fn[0]) strlcpy(upload_filename, fn, sizeof(upload_filename));
        }
        p = next_bdry + bdlen;
        if (p[0] == '-' && p[1] == '-') break;
        if (p[0] == '\r' && p[1] == '\n') p += 2;
        else break;
    }

    if (!file_data || upload_filename[0] == '\0') {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"no file\"}", 30);
        return;
    }
    if (strstr(upload_filename, "/") || strstr(upload_filename, "..")) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"invalid name\"}", 35);
        return;
    }

    char dest[192];
    DiagSnPrintf(dest, sizeof(dest), "%s/%s", LUA_SKILLS_DIR, upload_filename);
    mkdir(LUA_SKILLS_DIR, 0777);
    FILE *f = fopen(dest, "wb");
    if (!f) {
        send_fn(sock, 500, "application/json", "{\"ok\":false,\"error\":\"cannot write\"}", 35);
        return;
    }
    size_t wr2 = fwrite(file_data, 1, file_data_len, f);
    fclose(f);
    if (wr2 != file_data_len) {
        send_fn(sock, 500, "application/json",
                "{\"ok\":false,\"error\":\"write incomplete\"}", 39);
        return;
    }
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* ---- Lua driver module management (/api/lua/modules) ---- */

/* GET /api/lua/modules → {modules:[{id,category,enabled,locked,chip_ok},...],disabled:"..."} */
static void handle_api_lua_modules_get(const claw_http_request_t *req,
                                        claw_http_send_fn_t send_fn, int sock)
{
    (void)req;
    const char *disabled = claw_config_get()->lua.disabled_modules;
    size_t i, n = 0;
    const lua_module_desc_t *mods = lua_module_registry(&n);

    cJSON *resp = cJSON_CreateObject();
    cJSON *arr  = cJSON_CreateArray();
    if (!resp || !arr) {
        cJSON_Delete(resp); cJSON_Delete(arr);
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        return;
    }
    cJSON_AddItemToObject(resp, "modules", arr);

    for (i = 0; i < n; i++) {
        int chip_ok;
        int enabled;
        cJSON *m;
        /* Expose only REPL-environment modules; skip internal-only (TIMER-only) entries */
        if (!(mods[i].env_flags & LUA_MOD_ENV_REPL)) continue;
        /* Skip the virtual 'button' entry — it shares the gpio switch */
        if (strcmp(mods[i].name, "button") == 0) continue;

        chip_ok = lua_module_registry_chip_ok(mods[i].chip_peripheral);
        enabled = chip_ok &&
                  (mods[i].locked || !lua_module_registry_csv_contains(disabled, mods[i].name));

        m = cJSON_CreateObject();
        if (!m) continue;
        cJSON_AddStringToObject(m, "id",       mods[i].name);
        cJSON_AddStringToObject(m, "category",
                                mods[i].category == LUA_MOD_CAT_DRV    ? "drv" :
                                mods[i].category == LUA_MOD_CAT_DEV ? "dev" : "sw");
        cJSON_AddBoolToObject(  m, "enabled",  enabled);
        cJSON_AddBoolToObject(  m, "locked",   mods[i].locked || !chip_ok);
        cJSON_AddBoolToObject(  m, "chip_ok",  chip_ok);
        cJSON_AddItemToArray(arr, m);
    }
    cJSON_AddStringToObject(resp, "disabled", disabled ? disabled : "");

    {
        char *out = cJSON_PrintUnformatted(resp);
        cJSON_Delete(resp);
        if (out) {
            send_fn(sock, 200, "application/json", out, strlen(out));
            free(out);
        } else {
            send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        }
    }
}

/* POST /api/lua/modules  body:{disabled:"uart,spi"} → {ok:true} */
static void handle_api_lua_modules_post(const claw_http_request_t *req,
                                         claw_http_send_fn_t send_fn, int sock)
{
    cJSON *root;
    cJSON *disabled_j;
    const char *new_disabled;
    int rc;

    if (!req->body || req->body_len == 0) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"no body\"}", 30);
        return;
    }

    root = cJSON_ParseWithLength(req->body, req->body_len);
    if (!root) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"invalid json\"}", 35);
        return;
    }

    disabled_j = cJSON_GetObjectItemCaseSensitive(root, "disabled");
    if (!disabled_j || !cJSON_IsString(disabled_j)) {
        cJSON_Delete(root);
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"disabled field required\"}", 45);
        return;
    }
    new_disabled = disabled_j->valuestring ? disabled_j->valuestring : "";

    /* Strip chip-unsupported and locked modules from the disabled list before
     * storing: chip_ok=false modules cannot be user-toggled (always absent);
     * locked modules must stay enabled regardless. */
    {
        char *filtered = rtos_mem_malloc(CLAW_LUA_DISABLED_MODULES_SIZE);
        if (!filtered) {
            cJSON_Delete(root);
            send_fn(sock, 500, "application/json", "{\"ok\":false,\"error\":\"oom\"}", 24);
            return;
        }
        size_t flen = 0;
        size_t n = 0;
        const lua_module_desc_t *mods = lua_module_registry(&n);
        const char *p = new_disabled;
        while (*p) {
            const char *start;
            size_t tlen;
            size_t j;
            while (*p == ' ' || *p == ',') p++;
            if (!*p) break;
            start = p;
            while (*p && *p != ',') p++;
            tlen = (size_t)(p - start);
            while (tlen > 0 && start[tlen - 1] == ' ') tlen--;
            if (tlen == 0) continue;
            /* Check against registry: skip if locked or chip not supported */
            for (j = 0; j < n; j++) {
                if (strlen(mods[j].name) == tlen &&
                    strncmp(mods[j].name, start, tlen) == 0) {
                    if (mods[j].locked) goto next_token;
                    if (lua_module_registry_chip_ok(mods[j].chip_peripheral) <= 0) goto next_token;
                    break;
                }
            }
            if (flen > 0 && flen < CLAW_LUA_DISABLED_MODULES_SIZE - 1U) filtered[flen++] = ',';
            if (flen + tlen < CLAW_LUA_DISABLED_MODULES_SIZE - 1U) {
                memcpy(filtered + flen, start, tlen);
                flen += tlen;
            }
next_token:;
        }
        filtered[flen] = '\0';
        cJSON_Delete(root);
        rc = claw_config_set_lua_modules(filtered);
        if (rc == 0) {
            lua_module_registry_set_disabled(filtered);
        }
        rtos_mem_free(filtered);
    }

    if (rc != 0) {
        send_fn(sock, 500, "application/json", "{\"ok\":false,\"error\":\"save failed\"}", 34);
        return;
    }
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* DELETE /api/lua?name=xxx → {ok:true} */
static void handle_api_lua_delete(const claw_http_request_t *req,
                                    claw_http_send_fn_t send_fn, int sock)
{
    char enc[128], name[128];
    if (!query_get(req->query, "name", enc, sizeof(enc))) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"name required\"}", 36);
        return;
    }
    url_decode(enc, name, sizeof(name));
    if (!lua_name_safe(name)) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"invalid name\"}", 35);
        return;
    }

    char path[192];
    DiagSnPrintf(path, sizeof(path), "%s/%s", LUA_SKILLS_DIR, name);
    if (remove(path) != 0) {
        send_fn(sock, 500, "application/json", "{\"ok\":false,\"error\":\"delete failed\"}", 36);
        return;
    }
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* ---- Cap group visibility management ---- */

/* GET /api/cap/groups  →  [{group_id, plugin_name, runtime_enabled, llm_visible, is_core, tools[]}]
 *
 * Source of truth for the group list is claw_cap_registry (all compiled-in caps,
 * including runtime-disabled ones). claw_cap_list_groups() is used only to overlay
 * plugin_name and tool names for caps that are currently active (runtime_enabled).
 * This ensures runtime-disabled caps still appear in the UI so the user can re-enable
 * them. Kconfig-disabled caps are absent from the registry and are never shown. */
static void handle_api_cap_groups_get(const claw_http_request_t *req,
                                       claw_http_send_fn_t send_fn, int sock)
{
    (void)req;

    /* All compiled-in group IDs (from constructors, regardless of runtime state). */
    const char *reg_groups[CLAW_CAP_REGISTRY_MAX];
    size_t reg_count = claw_cap_registry_list_groups(reg_groups, CLAW_CAP_REGISTRY_MAX);

    /* Active groups snapshot for overlay (plugin_name, tools). */
    claw_cap_group_list_t active = claw_cap_list_groups();
#ifdef CONFIG_CLAW_CAP_SKILL_MGR
    const claw_cap_visibility_config_t *vis = &claw_config_get()->cap_visibility;
#endif
    const claw_cap_runtime_config_t    *rt  = &claw_config_get()->cap_runtime;

    cJSON *arr = cJSON_CreateArray();
    if (!arr) {
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        return;
    }

    for (size_t i = 0; i < reg_count; i++) {
        const char *gid = reg_groups[i];

        bool rt_disabled = false;
        for (uint8_t r = 0; r < rt->disabled_count; r++) {
            if (strcmp(rt->disabled[r], gid) == 0) { rt_disabled = true; break; }
        }

#ifdef CONFIG_CLAW_CAP_SKILL_MGR
        bool hidden  = cap_skill_mgr_group_is_hidden(gid, vis);
#else
        bool hidden  = false;
#endif
        bool is_core = claw_cap_registry_group_is_core(gid);

        /* Find the active group entry (absent when runtime-disabled). */
        const claw_cap_group_info_t *ag = NULL;
        for (size_t k = 0; k < active.count; k++) {
            if (active.items[k].group_id && strcmp(active.items[k].group_id, gid) == 0) {
                ag = &active.items[k];
                break;
            }
        }

        cJSON *obj = cJSON_CreateObject();
        cJSON_AddStringToObject(obj, "group_id",        gid);
        cJSON_AddStringToObject(obj, "plugin_name",     ag && ag->plugin_name ? ag->plugin_name : "");
        cJSON_AddBoolToObject  (obj, "runtime_enabled", !rt_disabled);
        cJSON_AddBoolToObject  (obj, "llm_visible",     !hidden);
        cJSON_AddBoolToObject  (obj, "is_core",         is_core);

        cJSON *tools_arr = cJSON_CreateArray();
        if (ag) {
            const char *tool_names[32];
            size_t tool_count = claw_cap_list_group_tools(gid, tool_names,
                                                           sizeof(tool_names) / sizeof(tool_names[0]));
            for (size_t t = 0; t < tool_count; t++) {
                cJSON_AddItemToArray(tools_arr, cJSON_CreateString(tool_names[t]));
            }
        }
        cJSON_AddItemToObject(obj, "tools", tools_arr);

        cJSON_AddItemToArray(arr, obj);
    }

    char *out = cJSON_PrintUnformatted(arr);
    cJSON_Delete(arr);
    if (!out) {
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        return;
    }
    send_fn(sock, 200, "application/json", out, strlen(out));
    free(out);
}

/* POST /api/cap/groups/visibility  body:{"hidden":["group_a","group_b"]}  →  {"ok":true} */
static void handle_api_cap_groups_visibility_post(const claw_http_request_t *req,
                                                   claw_http_send_fn_t send_fn, int sock)
{
    if (!req->body || req->body_len == 0) {
        send_json_err(send_fn, sock, 400, "empty body");
        return;
    }
    cJSON *root = cJSON_ParseWithLength(req->body, req->body_len);
    if (!root) {
        send_json_err(send_fn, sock, 400, "invalid JSON");
        return;
    }
    cJSON *hidden_j = cJSON_GetObjectItemCaseSensitive(root, "hidden");
    if (!hidden_j || !cJSON_IsArray(hidden_j)) {
        cJSON_Delete(root);
        send_json_err(send_fn, sock, 400, "hidden array required");
        return;
    }

    const char *groups[CLAW_CAP_HIDDEN_MAX];
    uint8_t count = 0;
    cJSON *it;
    cJSON_ArrayForEach(it, hidden_j) {
        if (!cJSON_IsString(it) || !it->valuestring) continue;
        if (count >= CLAW_CAP_HIDDEN_MAX) break;
        groups[count++] = it->valuestring;
    }
    int rc = claw_config_set_cap_visibility(groups, count);
    cJSON_Delete(root);
    if (rc != RTK_SUCCESS) {
        send_json_err(send_fn, sock, 500, "save failed");
        return;
    }
#ifdef CONFIG_CLAW_CAP_SKILL_MGR
    cap_skill_mgr_apply_base_visibility();
#endif
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* POST /api/cap/groups/runtime  body:{"disabled":["group_a",...]}  →  {"ok":true}
 * Persists runtime disabled list; takes effect on next boot. */
static void handle_api_cap_groups_runtime_post(const claw_http_request_t *req,
                                                claw_http_send_fn_t send_fn, int sock)
{
    if (!req->body || req->body_len == 0) {
        send_json_err(send_fn, sock, 400, "empty body");
        return;
    }
    cJSON *root = cJSON_ParseWithLength(req->body, req->body_len);
    if (!root) {
        send_json_err(send_fn, sock, 400, "invalid JSON");
        return;
    }
    cJSON *disabled_j = cJSON_GetObjectItemCaseSensitive(root, "disabled");
    if (!disabled_j || !cJSON_IsArray(disabled_j)) {
        cJSON_Delete(root);
        send_json_err(send_fn, sock, 400, "disabled array required");
        return;
    }

    const char *groups[CLAW_CAP_RUNTIME_DISABLED_MAX];
    uint8_t count = 0;
    cJSON *it;
    cJSON_ArrayForEach(it, disabled_j) {
        if (!cJSON_IsString(it) || !it->valuestring) continue;
        if (count >= CLAW_CAP_RUNTIME_DISABLED_MAX) break;
        /* Core caps cannot be runtime-disabled; silently skip them. */
        if (claw_cap_registry_group_is_core(it->valuestring)) continue;
        groups[count++] = it->valuestring;
    }
    int rc = claw_config_set_cap_runtime_disabled(groups, count);
    cJSON_Delete(root);
    if (rc != RTK_SUCCESS) {
        send_json_err(send_fn, sock, 500, "save failed");
        return;
    }
    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
}

/* ---- Direct cap invocation (for testing/debugging) ---- */

/* POST /api/cap/invoke  body:{cap:"name", input:{...}} → cap output JSON */
static void handle_api_cap_invoke(const claw_http_request_t *req,
                                   claw_http_send_fn_t send_fn, int sock)
{
    if (!req->body || req->body_len == 0) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"no body\"}", 30);
        return;
    }

    cJSON *root = cJSON_ParseWithLength(req->body, req->body_len);
    if (!root) {
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"invalid json\"}", 35);
        return;
    }

    cJSON *cap_j   = cJSON_GetObjectItemCaseSensitive(root, "cap");
    cJSON *input_j = cJSON_GetObjectItemCaseSensitive(root, "input");

    if (!cap_j || !cJSON_IsString(cap_j)) {
        cJSON_Delete(root);
        send_fn(sock, 400, "application/json", "{\"ok\":false,\"error\":\"cap required\"}", 35);
        return;
    }

    const char *cap_name = cap_j->valuestring;
    char *input_str = NULL;
    if (input_j) {
        input_str = cJSON_PrintUnformatted(input_j);
    }
    cJSON_Delete(root);

    char *output = NULL;
    static const claw_cap_call_context_t s_test_ctx = {
        .session_id = "local:local:default",
        .channel    = "local",
        .chat_id    = "local",
        .caller     = CLAW_CAP_CALLER_MANUAL,
    };

    int rc = claw_cap_call(cap_name, input_str ? input_str : "{}", &s_test_ctx, &output);
    free(input_str);

    if (output) {
        send_fn(sock, rc == 0 ? 200 : 500, "application/json", output, strlen(output));
        free(output);
    } else {
        send_fn(sock, 500, "application/json", "{\"error\":\"no output\"}", 21);
    }
}

/* ---- Session management handlers ---- */

#define WS_SESSION_CHANNEL  "local"
#define WS_SESSION_CHAT_ID  "local"

/* GET /api/sessions — returns all channels and their sessions (no preview, fast) */
static void handle_api_sessions_get(const claw_http_request_t *req,
                                     claw_http_send_fn_t send_fn, int sock)
{
    (void)req;
    const char *sroot = claw_memory_get_session_root();
    char *map_dir = (char *)rtos_mem_malloc(256);
    if (!map_dir) {
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        return;
    }
    DiagSnPrintf(map_dir, 256, "%s/chat_map", sroot);

    cJSON *root = cJSON_CreateObject();
    cJSON *channels = cJSON_CreateArray();
    if (!root || !channels) {
        cJSON_Delete(root);
        cJSON_Delete(channels);
        rtos_mem_free(map_dir);
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
        return;
    }
    cJSON_AddBoolToObject(root, "ok", 1);
    cJSON_AddItemToObject(root, "channels", channels);

    void *dir = opendir(map_dir);
    if (dir) {
        struct dirent *ent;
        while ((ent = readdir(dir)) != NULL) {
            if (ent->d_type == DT_DIR) continue;
            size_t nlen = strlen(ent->d_name);
            if (nlen < 5 || strcmp(ent->d_name + nlen - 5, ".json") != 0) continue;

            char *fpath = (char *)rtos_mem_malloc(320);
            if (!fpath) continue;
            DiagSnPrintf(fpath, 320, "%s/%s", map_dir, ent->d_name);

            char *fbuf = (char *)rtos_mem_malloc(1024);
            if (!fbuf) { rtos_mem_free(fpath); continue; }
            FILE *f = fopen(fpath, "r");
            rtos_mem_free(fpath);
            if (!f) { rtos_mem_free(fbuf); continue; }
            size_t nread = fread(fbuf, 1, 1023, f);
            fclose(f);
            fbuf[nread] = '\0';

            cJSON *map = cJSON_Parse(fbuf);
            rtos_mem_free(fbuf);
            if (!map) continue;

            cJSON *jkey  = cJSON_GetObjectItem(map, "chat_key");
            cJSON *jcur  = cJSON_GetObjectItem(map, "current");
            cJSON *jsess = cJSON_GetObjectItem(map, "sessions");

            cJSON *entry = cJSON_CreateObject();
            if (entry) {
                cJSON_AddStringToObject(entry, "chat_key",
                    (jkey && cJSON_IsString(jkey)) ? jkey->valuestring : "");
                cJSON_AddStringToObject(entry, "current",
                    (jcur && cJSON_IsString(jcur)) ? jcur->valuestring : "default");
                cJSON *sarr = cJSON_CreateArray();
                if (sarr && jsess && cJSON_IsArray(jsess)) {
                    cJSON *it;
                    cJSON_ArrayForEach(it, jsess) {
                        if (cJSON_IsString(it))
                            cJSON_AddItemToArray(sarr, cJSON_CreateString(it->valuestring));
                    }
                }
                cJSON_AddItemToObject(entry, "sessions", sarr ? sarr : cJSON_CreateArray());
                cJSON_AddItemToArray(channels, entry);
            }
            cJSON_Delete(map);
        }
        closedir(dir);
    }
    rtos_mem_free(map_dir);

    char *out = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (out) {
        send_fn(sock, 200, "application/json", out, strlen(out));
        free(out);
    } else {
        send_fn(sock, 500, "application/json", "{\"error\":\"oom\"}", 15);
    }
}

/* GET /api/session/history?session_id=channel:chat_id:alias */
static void handle_api_session_history_get(const claw_http_request_t *req,
                                            claw_http_send_fn_t send_fn, int sock)
{
    char enc[192], session_id[192];
    if (!query_get(req->query, "session_id", enc, sizeof(enc))) {
        send_json_err(send_fn, sock, 400, "session_id required");
        return;
    }
    url_decode(enc, session_id, sizeof(session_id));

    char *turns_json = claw_memory_read_session_json(session_id, NULL, 0);
    if (!turns_json) {
        send_fn(sock, 200, "application/json", "{\"ok\":true,\"turns\":[]}", 21);
        return;
    }

    /* Construct: {"ok":true,"turns":<turns_json>} without double-parsing */
    static const char s_prefix[] = "{\"ok\":true,\"turns\":";
    size_t plen = sizeof(s_prefix) - 1;
    size_t tlen = strlen(turns_json);
    char *resp = (char *)rtos_mem_malloc(plen + tlen + 2);
    if (!resp) {
        free(turns_json);
        send_json_err(send_fn, sock, 500, "oom");
        return;
    }
    _memcpy(resp, s_prefix, plen);
    _memcpy(resp + plen, turns_json, tlen);
    resp[plen + tlen]     = '}';
    resp[plen + tlen + 1] = '\0';
    free(turns_json);

    send_fn(sock, 200, "application/json", resp, plen + tlen + 1);
    rtos_mem_free(resp);
}

/* Parse text output of cap_session_mgr_list into a cJSON array of alias strings.
 * Each line has format "• <name>\n" or "• <name> (current)\n".
 * The bullet is UTF-8: 0xE2 0x80 0xA2 followed by 0x20 (4 bytes total). */
static cJSON *parse_session_list_to_json(const char *list_text)
{
    cJSON *arr = cJSON_CreateArray();
    if (!arr) {
        return arr;
    }
    const char *p = list_text;
    while (p && *p) {
        /* Each line starts with the bullet sequence (4 bytes). */
        if ((unsigned char)p[0] == 0xE2 && (unsigned char)p[1] == 0x80 &&
                (unsigned char)p[2] == 0xA2 && p[3] == ' ') {
            const char *alias_start = p + 4;
            const char *nl = strchr(alias_start, '\n');
            size_t len = nl ? (size_t)(nl - alias_start) : strlen(alias_start);
            /* Strip trailing '\r' */
            if (len > 0 && alias_start[len - 1] == '\r') {
                len--;
            }
            /* Strip " (current)" suffix (10 bytes) */
            const char *cur_sfx = " (current)";
            size_t sfx_len = 10;
            if (len >= sfx_len && strncmp(alias_start + len - sfx_len, cur_sfx, sfx_len) == 0) {
                len -= sfx_len;
            }
            /* Build alias string */
            char alias_buf[64];
            if (len >= sizeof(alias_buf)) {
                len = sizeof(alias_buf) - 1;
            }
            _memcpy(alias_buf, alias_start, len);
            alias_buf[len] = '\0';
            cJSON_AddItemToArray(arr, cJSON_CreateString(alias_buf));
        }
        /* Advance to next line */
        const char *nl = strchr(p, '\n');
        p = nl ? nl + 1 : NULL;
    }
    return arr;
}

/* Fill out[0..out_size-1] with the first user message text for the given alias.
 * Reads the session file; sets out[0]='\0' when no history exists. */
static void get_session_preview(const char *alias, char *out, size_t out_size)
{
    char sid[96];
    out[0] = '\0';
    DiagSnPrintf(sid, sizeof(sid), "%s:%s:%s", WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID, alias);
    char *hist = claw_memory_read_session_json(sid, out, out_size);
    if (hist) {
        free(hist);
    }
}

/* Convert an alias-string cJSON array to [{alias,preview}] objects. Deletes alias_arr. */
static cJSON *sessions_with_preview(cJSON *alias_arr)
{
    cJSON *out = cJSON_CreateArray();
    if (!out) {
        cJSON_Delete(alias_arr);
        return NULL;
    }
    char preview[64];
    cJSON *item;
    cJSON_ArrayForEach(item, alias_arr) {
        const char *alias = cJSON_GetStringValue(item);
        if (!alias) {
            continue;
        }
        get_session_preview(alias, preview, sizeof(preview));
        cJSON *obj = cJSON_CreateObject();
        if (obj) {
            cJSON_AddStringToObject(obj, "alias", alias);
            cJSON_AddStringToObject(obj, "preview", preview);
            cJSON_AddItemToArray(out, obj);
        }
    }
    cJSON_Delete(alias_arr);
    return out;
}

/* Broadcast a session_snapshot WS message to all /ws/chat clients.
 * alias: the newly-active session alias. */
static void broadcast_session_snapshot(const char *alias)
{
    char *list_buf = rtos_mem_malloc(512);
    if (!list_buf) {
        return;
    }
    cap_session_mgr_list(WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID, list_buf, 512);
    cJSON *sessions_arr = parse_session_list_to_json(list_buf);
    rtos_mem_free(list_buf);

    cJSON *root = cJSON_CreateObject();
    if (!root) {
        cJSON_Delete(sessions_arr);
        return;
    }
    cJSON_AddStringToObject(root, "type", "session_snapshot");
    cJSON_AddStringToObject(root, "current", alias);
    cJSON_AddItemToObject(root, "sessions", sessions_with_preview(sessions_arr));

    char *j = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (j) {
        claw_ws_broadcast_text("/ws/chat", j, strlen(j));
        free(j);
    }
}

/* GET /api/session — returns current session and non-empty session list */
static void handle_api_session_get(const claw_http_request_t *req,
                                    claw_http_send_fn_t send_fn, int sock)
{
    char *list_buf = rtos_mem_malloc(512);
    if (!list_buf) {
        send_json_err(send_fn, sock, 500, "oom");
        return;
    }
    int list_len = cap_session_mgr_list(WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID, list_buf, 512);

    if (list_len == 0 && list_buf[0] == '\0') {
        rtos_mem_free(list_buf);
        const char *empty_resp = "{\"ok\":true,\"current\":\"default\",\"sessions\":[\"default\"]}";
        send_fn(sock, 200, "application/json", empty_resp, strlen(empty_resp));
        return;
    }

    cJSON *sessions_arr = parse_session_list_to_json(list_buf);
    rtos_mem_free(list_buf);

    char cur_alias[40] = "default";
    if (cap_session_mgr_get_current(WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID,
                                    cur_alias, sizeof(cur_alias)) != RTK_SUCCESS) {
        RTK_LOGE(TAG, "get_current failed, using default\n");
    }

    cJSON *root = cJSON_CreateObject();
    if (!root) {
        cJSON_Delete(sessions_arr);
        send_json_err(send_fn, sock, 500, "oom");
        return;
    }
    cJSON_AddBoolToObject(root, "ok", 1);
    cJSON_AddStringToObject(root, "current", cur_alias);
    cJSON_AddItemToObject(root, "sessions", sessions_with_preview(sessions_arr));

    char *resp = cJSON_PrintUnformatted(root);
    cJSON_Delete(root);
    if (resp) {
        send_fn(sock, 200, "application/json", resp, strlen(resp));
        free(resp);
    } else {
        send_json_err(send_fn, sock, 500, "oom");
    }
}

/* POST /api/session — session management actions */
static void handle_api_session_post(const claw_http_request_t *req,
                                     claw_http_send_fn_t send_fn, int sock)
{
    if (!req->body || req->body_len == 0) {
        send_json_err(send_fn, sock, 400, "no body");
        return;
    }
    cJSON *root = cJSON_ParseWithLength(req->body, req->body_len);
    if (!root) {
        send_json_err(send_fn, sock, 400, "invalid json");
        return;
    }
    cJSON *action_j = cJSON_GetObjectItemCaseSensitive(root, "action");
    cJSON *alias_j  = cJSON_GetObjectItemCaseSensitive(root, "alias");

    if (!action_j || !cJSON_IsString(action_j)) {
        cJSON_Delete(root);
        send_json_err(send_fn, sock, 400, "action required");
        return;
    }

    const char *action = action_j->valuestring;

    if (strcmp(action, "new") == 0) {
        char out_alias[40];
        _memset(out_alias, 0, sizeof(out_alias));
        int rc = cap_session_mgr_new(WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID,
                                     (alias_j && cJSON_IsString(alias_j)) ? alias_j->valuestring : NULL,
                                     out_alias, sizeof(out_alias));
        cJSON_Delete(root);
        if (rc == CAP_SESSION_ERR_CONFLICT) {
            send_json_err(send_fn, sock, 409, "session already exists");
            return;
        } else if (rc != RTK_SUCCESS) {
            send_json_err(send_fn, sock, 500, "new session failed");
            return;
        }
        cJSON *resp = cJSON_CreateObject();
        if (resp) {
            cJSON_AddBoolToObject(resp, "ok", 1);
            cJSON_AddStringToObject(resp, "alias", out_alias);
            char *s = cJSON_PrintUnformatted(resp);
            cJSON_Delete(resp);
            if (s) {
                send_fn(sock, 200, "application/json", s, strlen(s));
                free(s);
                broadcast_session_snapshot(out_alias);
                return;
            }
        }
        send_json_err(send_fn, sock, 500, "oom");

    } else if (strcmp(action, "resume") == 0) {
        if (!alias_j || !cJSON_IsString(alias_j)) {
            cJSON_Delete(root);
            send_json_err(send_fn, sock, 400, "alias required");
            return;
        }
        char alias_buf[40];
        DiagSnPrintf(alias_buf, sizeof(alias_buf), "%s", alias_j->valuestring);
        int rc = cap_session_mgr_resume(WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID, alias_buf);
        cJSON_Delete(root);
        if (rc == CAP_SESSION_ERR_NOT_FOUND) {
            send_json_err(send_fn, sock, 404, "not found");
            return;
        } else if (rc != RTK_SUCCESS) {
            send_json_err(send_fn, sock, 500, "resume failed");
            return;
        }
        send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
        broadcast_session_snapshot(alias_buf);

    } else if (strcmp(action, "rename") == 0) {
        if (!alias_j || !cJSON_IsString(alias_j)) {
            cJSON_Delete(root);
            send_json_err(send_fn, sock, 400, "alias required");
            return;
        }
        const char *alias = alias_j->valuestring;
        int rc = cap_session_mgr_rename(WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID, alias);
        cJSON_Delete(root);
        if (rc == CAP_SESSION_ERR_CONFLICT) {
            send_json_err(send_fn, sock, 409, "name conflict");
            return;
        } else if (rc != RTK_SUCCESS) {
            send_json_err(send_fn, sock, 500, "rename failed");
            return;
        }
        char new_alias[40] = "default";
        if (cap_session_mgr_get_current(WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID,
                                        new_alias, sizeof(new_alias)) != RTK_SUCCESS) {
            RTK_LOGE(TAG, "get_current failed after rename\n");
        }
        send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
        broadcast_session_snapshot(new_alias);

    } else if (strcmp(action, "clear") == 0) {
        cJSON_Delete(root);
        char cur_alias[40] = "default";
        cap_session_mgr_get_current(WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID,
                                    cur_alias, sizeof(cur_alias));
        int rc = cap_session_mgr_clear_chat(WS_SESSION_CHANNEL, WS_SESSION_CHAT_ID);
        if (rc != RTK_SUCCESS) {
            send_json_err(send_fn, sock, 500, "clear failed");
            return;
        }
#ifdef CONFIG_CLAW_CAP_IM_LOCAL
        cap_im_local_clear_alias(cur_alias);
#endif
        send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);
        broadcast_session_snapshot(cur_alias);

    } else {
        cJSON_Delete(root);
        send_json_err(send_fn, sock, 400, "unknown action");
    }
}

/* DELETE /api/session?alias=X[&channel=Y&chat_id=Z] — delete a session */
static void handle_api_session_delete(const claw_http_request_t *req,
                                       claw_http_send_fn_t send_fn, int sock)
{
    char enc[64], alias[64], enc2[64];
    char channel_buf[64], chat_id_buf[64];

    if (!query_get(req->query, "alias", enc, sizeof(enc))) {
        send_json_err(send_fn, sock, 400, "alias required");
        return;
    }
    url_decode(enc, alias, sizeof(alias));

    /* Optional channel/chat_id; default to local:local */
    strlcpy(channel_buf, WS_SESSION_CHANNEL, sizeof(channel_buf));
    strlcpy(chat_id_buf, WS_SESSION_CHAT_ID, sizeof(chat_id_buf));
    if (query_get(req->query, "channel", enc2, sizeof(enc2)))
        url_decode(enc2, channel_buf, sizeof(channel_buf));
    if (query_get(req->query, "chat_id", enc2, sizeof(enc2)))
        url_decode(enc2, chat_id_buf, sizeof(chat_id_buf));

    int rc = cap_session_mgr_delete(channel_buf, chat_id_buf, alias);
    if (rc == CAP_SESSION_ERR_NOT_FOUND) {
        send_json_err(send_fn, sock, 404, "not found");
        return;
    } else if (rc != RTK_SUCCESS) {
        send_json_err(send_fn, sock, 500, "delete failed");
        return;
    }

    send_fn(sock, 200, "application/json", "{\"ok\":true}", 11);

    /* Broadcast to WebSocket clients only for local:local sessions */
    bool is_local = (strcmp(channel_buf, WS_SESSION_CHANNEL) == 0 &&
                     strcmp(chat_id_buf, WS_SESSION_CHAT_ID) == 0);
    if (is_local) {
        cJSON *del_msg = cJSON_CreateObject();
        if (del_msg) {
            cJSON_AddStringToObject(del_msg, "type", "session_deleted");
            cJSON_AddStringToObject(del_msg, "alias", alias);
            char *msg_str = cJSON_PrintUnformatted(del_msg);
            cJSON_Delete(del_msg);
            if (msg_str) {
                claw_ws_broadcast_text("/ws/chat", msg_str, strlen(msg_str));
                free(msg_str);
            }
        }
        char new_cur[40] = WS_SESSION_CHAT_ID;
        cap_session_mgr_get_current(channel_buf, chat_id_buf, new_cur, sizeof(new_cur));
        broadcast_session_snapshot(new_cur);
    }
}

/* ---- Public API ---- */

int cap_webui_init(void)
{
    int rc = 0;
    rc |= claw_http_server_add_route(HTTP_GET,  "/favicon.ico",        handle_favicon);
    rc |= claw_http_server_add_route(HTTP_GET,  "/",                   handle_index);
    rc |= claw_http_server_add_route(HTTP_GET,  "/status",             handle_status);
    rc |= claw_http_server_add_route(HTTP_GET,  "/setup",              handle_index);
    rc |= claw_http_server_add_route(HTTP_POST, "/setup",              handle_setup_post);
    rc |= claw_http_server_add_route(HTTP_GET,  "/api/config",         handle_api_config);
    rc |= claw_http_server_add_route(HTTP_POST, "/api/wifi/connect",   handle_wifi_connect);
    rc |= claw_http_server_add_route(HTTP_GET,  "/api/wifi/scan",      handle_wifi_scan);
    rc |= claw_http_server_add_route(HTTP_POST, "/api/system/restart", handle_system_restart);
#ifdef CONFIG_CLAW_CAP_IM_WECHAT
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/wechat/qrcode",      handle_wechat_qrcode);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/wechat/status",      handle_wechat_status);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/wechat/token",       handle_wechat_token_get);
#endif
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/files/regions",      handle_api_files_regions);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/files",              handle_api_files_get);
    rc |= claw_http_server_add_route(HTTP_DELETE, "/api/files",              handle_api_files_delete);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/files/download",     handle_api_files_download);
    rc |= claw_http_server_add_route(HTTP_POST,   "/api/files/mkdir",        handle_api_files_mkdir);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/files/content",      handle_api_files_content_get);
    rc |= claw_http_server_add_route(HTTP_PUT,    "/api/files/content",      handle_api_files_content_put);
    rc |= claw_http_server_add_route(HTTP_POST,   "/api/files/upload",       handle_api_files_upload);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/lua",                handle_api_lua_list);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/lua/content",        handle_api_lua_content_get);
    rc |= claw_http_server_add_route(HTTP_PUT,    "/api/lua/content",        handle_api_lua_content_put);
    rc |= claw_http_server_add_route(HTTP_POST,   "/api/lua/upload",         handle_api_lua_upload);
    rc |= claw_http_server_add_route(HTTP_DELETE, "/api/lua",                handle_api_lua_delete);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/lua/modules",        handle_api_lua_modules_get);
    rc |= claw_http_server_add_route(HTTP_POST,   "/api/lua/modules",        handle_api_lua_modules_post);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/cap/groups",                 handle_api_cap_groups_get);
    rc |= claw_http_server_add_route(HTTP_POST,   "/api/cap/groups/visibility",      handle_api_cap_groups_visibility_post);
    rc |= claw_http_server_add_route(HTTP_POST,   "/api/cap/groups/runtime",         handle_api_cap_groups_runtime_post);
    rc |= claw_http_server_add_route(HTTP_POST,   "/api/cap/invoke",                 handle_api_cap_invoke);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/sessions",           handle_api_sessions_get);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/session",            handle_api_session_get);
    rc |= claw_http_server_add_route(HTTP_GET,    "/api/session/history",    handle_api_session_history_get);
    rc |= claw_http_server_add_route(HTTP_POST,   "/api/session",            handle_api_session_post);
    rc |= claw_http_server_add_route(HTTP_DELETE, "/api/session",            handle_api_session_delete);
    if (rc != 0) {
        RTK_LOGE(TAG, "failed to register one or more routes\n");
        return RTK_FAIL;
    }
    RTK_LOGI(TAG, "routes registered: / /status /setup /api/config /api/wifi/* /api/files/* /api/sessions /api/session/*\n");
    return RTK_SUCCESS;
}

/* ---- Lifecycle registration (claw_cap_registry): IO phase (HTTP routes) ----
 * cap_webui registers no cap group (the `group` id is a label for the future
 * runtime enable-list). It registers HTTP routes, so it must run before
 * claw_http_server_start() — guaranteed by registry_run(IO)'s placement. */
static void webui_on_io(const claw_config_t *cfg)
{
    (void)cfg;
    cap_webui_init();
}
CLAW_CAP_REGISTER(webui, {
    .group = "webui",
    .flags = CLAW_CAP_FLAG_CORE,
    .order = 110,
    .on_io = webui_on_io,
});
