#!/usr/bin/env python3
"""Build WebUI: merge + minify src/*.{html,css,js} -> generated/dashboard_html.c

Usage: python3 build_html.py <src_dir> <output_c>
"""
import re
import sys
import os

JS_ORDER = [
    'utils.js',
    'nav.js',
    'status.js',
    'chat.js',
    'session.js',
    'network.js',
    'llm.js',
    'imbot.js',
    'search.js',
    'http_request.js',
    'tasks.js',
    'lua.js',
    'files.js',
    'memory.js',
    'session_mgr.js',
]


def strip_comments_and_blanks(text):
    """Strip standalone comment lines and blank lines.

    Only removes lines whose first non-whitespace characters are '//' or '/*'.
    Does not touch inline comments after code — safe without a real parser.
    Also strips CSS block comments (/* ... */) that span whole lines.
    """
    # Remove /* ... */ block comments (used as section headers in CSS/JS)
    text = re.sub(r'/\*[^*].*?\*/', '', text, flags=re.DOTALL)
    text = re.sub(r'/\*\*.*?\*/', '', text, flags=re.DOTALL)
    lines = []
    for line in text.split('\n'):
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith('//'):
            continue
        lines.append(line)
    return '\n'.join(lines)


def to_c_array(data, array_name, size_name):
    chunks = [data[i:i+16] for i in range(0, len(data), 16)]
    rows = [', '.join('0x{:02x}'.format(b) for b in chunk) for chunk in chunks]
    body = ',\n    '.join(rows)
    return (
        '/* Auto-generated by build_html.py — do not edit */\n'
        'const unsigned char {arr}[] = {{\n'
        '    {body}\n'
        '}};\n'
        'const unsigned int {sz} = sizeof({arr});\n'
    ).format(arr=array_name, body=body, sz=size_name)


def main():
    if len(sys.argv) != 3:
        print('Usage: build_html.py <src_dir> <output_c>', file=sys.stderr)
        sys.exit(1)

    src_dir = sys.argv[1]
    output_c = sys.argv[2]

    # Read and minify CSS
    css_path = os.path.join(src_dir, 'style.css')
    with open(css_path, 'r', encoding='utf-8') as f:
        css = strip_comments_and_blanks(f.read())

    # Read and concatenate JS in declared order
    js_parts = []
    for fname in JS_ORDER:
        js_path = os.path.join(src_dir, fname)
        with open(js_path, 'r', encoding='utf-8') as f:
            js_parts.append(strip_comments_and_blanks(f.read()))
    js = '\n'.join(js_parts)

    # Read HTML skeleton and inject CSS + JS
    html_path = os.path.join(src_dir, 'dashboard.html')
    with open(html_path, 'r', encoding='utf-8') as f:
        html = f.read()

    if '/*__STYLE__*/' not in html or '/*__JS__*/' not in html:
        print('ERROR: dashboard.html missing /*__STYLE__*/ or /*__JS__*/ placeholder',
              file=sys.stderr)
        sys.exit(1)

    html = html.replace('/*__STYLE__*/', css)
    html = html.replace('/*__JS__*/', js)

    # Encode, gzip-compress, and generate C array
    import gzip
    data = gzip.compress(html.encode('utf-8'), compresslevel=9)
    c_code = to_c_array(data, '_res_dashboard_html_start', '_res_dashboard_html_size')

    os.makedirs(os.path.dirname(output_c), exist_ok=True)
    with open(output_c, 'w', encoding='utf-8') as f:
        f.write(c_code)

    print('WebUI bundled: {} bytes (gzip) -> {}'.format(len(data), output_c))


if __name__ == '__main__':
    main()
